### ISSUE TITLE
Algorithm: Implement jump search algorithm in Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#10]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Implement Jump Search in Python

**what will change** - Create a New Folder `SeacrhingAlgorithms` In Python/Algorithms

**Assignees** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by devil-cyber** [comment]
Can I work on this

**Comment by codeperfectplus** [comment]
- [x] @devil-cyber  Issue assigning

**Comment by devil-cyber** [comment]
Thanks
