### ISSUE TITLE
Exponential Search | Searching Algorithm | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#100]
## **`Title`** - Exponential Search | Searching Algorithm | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Balaguru4580** [comment]
Hello. I'm willing to work on this. Is it possible for me to be assigned?

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @Balaguru4580

**Comment by p014ri5** [comment]
Hey can I get assigned too??
