### ISSUE TITLE
Count Inversions | Divide and Conquer | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#101]
## **`Title`** - Count Inversions | Divide and Conquer | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by thatAverageGuy** [comment]
I would like to work on this one.

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @mohityogesh44
