### ISSUE TITLE
Tiling Problem using Divide and Conquer algorithm | Divide and Conquer | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#103]
## **`Title`** - Tiling Problem using Divide and Conquer algorithm | Divide and Conquer | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by kashika3101** [comment]
I would like to contribute to this issue

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @kashika3101

**Comment by SSKale1** [comment]
PR merged
