### ISSUE TITLE
Tiling Problem  | Divide and Conquer | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#104]
## **`Title`** - Tiling Problem using Divide and Conquer algorithm | Divide and Conquer | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AnshMishra2001** [comment]
I want to work on this issue.

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @AnshMishra2001

**Comment by HIMANSHU3107** [comment]
I'd love to work on this
