### ISSUE TITLE
Bellman Ford Shortest Path Algorithm | Algorithm | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#106]
## **`Title`** - Find the shortest path in the graph using bellman ford algorithm

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ritikgarg655** [comment]
what will change - new python implementation file for bellman Ford algorithm. The worst case of this algorithm is equal to the O(nm). 

Type of Issue -
Please add/delete options that are not relevant.

[✓] Adding New Code
[ ] Improving Code
[ ] Improving Documentation
[ ] Bug Fix
Programming Language
Please add/delete options that are not relevant.

[✓] Python


Can I start working on this issue?

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue  to @ritikgarg655 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

**Comment by MannanAhmad** [comment]
can I work on this?

**Comment by ritikgarg655** [comment]
@shubham5351 Please review PR.
