### ISSUE TITLE
Recursive Sum | Recursion | C++

### ISSUE THREAD

**Issue by rajdeep-ray** [Py-Contributors/AlgorithmsAndDataStructure#107]
## **`Title`** - Recursive Sum | Recursion

I would like to add new code in the Algorithms folder for Recursion under C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rajdeep-ray** [comment]
I would like to work on this issue

**Comment by codeperfectplus** [comment]
@Rajdeep-Ray you already assigned to a lot of issues. please give a chance to new contributors too. 
Thanks

**Comment by kashika3101** [comment]
I would like to work on this issue.Can you please assign it to me?

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @kashika3101

**Comment by kashika3101** [comment]
Should we start making the PR to this issue from 1st October as a part of Hacktoberfest'20?

**Comment by codeperfectplus** [comment]
Ya create your PR between 1st October - 31 October. @kashika3101

**Comment by kashika3101** [comment]
if possible can you provide sample inputs?
@codePerfectPlus

**Comment by SSKale1** [comment]
I would like to contribute towards this issue. Can I be assigned to this?

**Comment by vvekparmar** [comment]
I would also like to contribute on this issue. Please assigned this to me?

**Comment by Neon-20** [comment]
Hey There !! @codePerfectPlus 
I would love to contribute in this since i am a newbie and try my hands on it.

**Comment by wjeevika** [comment]
I would like to contribute to this issue. May I?

**Comment by kashika3101** [comment]
Please review the PR #266
@Rajdeep-Ray @codePerfectPlus

**Comment by SSKale1** [comment]
PR has been merged.
