### ISSUE TITLE
Fibbonacci Search implementation in Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#11]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Fibbonacci Search implementation in Python

**what will change** - Fibbonacci Search implementation in Python

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by Jaideep07** [comment]
I would love to do this 😃 can you assign it to me

**Comment by codeperfectplus** [comment]
- [x] @Jaideep07 assigning task.

Happy coding,

**Comment by sourabmaity** [comment]
I would like to solve it

**Comment by Jaideep07** [comment]
I'm already done with it @SOURAB-BAPPA , waiting to make PR tomorrow 😜
