### ISSUE TITLE
Contribute to Repo 🤝

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#110]

**Comment by tenzu15** [comment]
Is this repo open for contribution? I would like to contribute by adding a basic CNN prototype using keras

**Comment by codeperfectplus** [comment]
@tenzu15 Sorry but we are implementing algorithms from scratch. you can't use the Keras LIB. If you like to add CNN you have to code it from scratch.
