### ISSUE TITLE
Longest Common Subsequence | Dynamic Programming | Python

### ISSUE THREAD

**Issue by meghanacosmos** [Py-Contributors/AlgorithmsAndDataStructure#111]
## **`Title`** - Longest Common Subsequence 

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by meghanacosmos** [comment]
I'd love to work on this.

**Comment by shubham5351** [comment]
@Meghana-12 you can work on this issue.

**Comment by meghanacosmos** [comment]
Thanks :)

**Comment by codeperfectplus** [comment]
@Meghana-12 Please create your pr using flake8 standards.  you can make PR from tomorrow

**Comment by meghanacosmos** [comment]
Sure, thanks for the review !
