### ISSUE TITLE
Merge Sort | Sorting | C++

### ISSUE THREAD

**Issue by cozyxss** [Py-Contributors/AlgorithmsAndDataStructure#112]
## **`Title`** - Merge Sort

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by cozyxss** [comment]
I'd love to work on this.

**Comment by frbio** [comment]
I can work on this.

**Comment by frbio** [comment]
Can you assign me this issue?

**Comment by codeperfectplus** [comment]
duplicate issue @bbetulkaya

**Comment by cozyxss** [comment]
sorry i didn't see that
