### ISSUE TITLE
Sudoku Solver | Backtracking | Python

### ISSUE THREAD

**Issue by Swapnil-2001** [Py-Contributors/AlgorithmsAndDataStructure#113]
## **`Title`** - Sudoku Solver

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Swapnil-2001** [comment]
I would like to add an implementation of Sudoku Solver in Python. I would be glad if I am assigned this.

**Comment by codeperfectplus** [comment]
- [x] Issue assigning to @Swapnil-2001
