### ISSUE TITLE
Sum of digits of Random three digit number | Algorithm | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#114]
I would like to work on this issue.

## **`Title`** - Calculate sum of each digit from the 3 digit numbers

Input : 389

Output : 20

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Aairah-iiitd** [comment]
I would like to work on this

**Comment by Shreyansh252001** [comment]
hi, @shubham5351 i would love to work on this issue !!!according to my understanding this issue contains problem of summing up 3 digits of a number to a specific sum!!!

**Comment by Taneesha-creates** [comment]
I would like to work on this for hacktoberfest, can you assign it to me?

**Comment by sourabmaity** [comment]
i would like to code for this

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @Aairah-iiitd based on the comment priority.

**Comment by TheCoderNikhil** [comment]
I will also like to contribute

**Comment by shubham5351** [comment]
So Guys you can create same issue but in C++ and will be assigned on FCFS basis.

**Comment by wjeevika** [comment]
I would like to contribute to this issue. May I?

**Comment by Deephacks619** [comment]
I wanna work on this issue. Please assign the task to me.
