### ISSUE TITLE
Coin Change | Dynamic Programming | Python

### ISSUE THREAD

**Issue by Swapnil-2001** [Py-Contributors/AlgorithmsAndDataStructure#117]
## **`Title`** - Coin Change

**what will change** - Given coins of different denominations and a total amount of money, this algorithm computes the fewest number of coins needed to make up that amount.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Swapnil-2001** [comment]
I would like to work on this, if assigned.

**Comment by SOURAB-BAPPA** [comment]
i want to solve it

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @Swapnil-2001

**Comment by Ishita-0112** [comment]
I would love to add the two variations of Coin Change problem - Maximum Number of ways & Minimum number of Coins. If you would kindly assign me this issue.

**Comment by shubham5351** [comment]
Hi @Ishita-0112 as this problem is already assigned to @Swapnil-2001 after his PR, if there is some improvement then you can work on it as of now you can create some new issue.

**Comment by Ishita-0112** [comment]
> 
> 
> Hi @Ishita-0112 as this problem is already assigned to @Swapnil-2001 after his PR, if there is some improvement then you can work on it as of now you can create some new issue.

Okay sure got it. Thanks.
