### ISSUE TITLE
Sequential Search | Searching Algorithms | Python

### ISSUE THREAD

**Issue by akhileshsantoshwar** [Py-Contributors/AlgorithmsAndDataStructure#118]
## **`Title`** - Sequential Search | Searching Algorithms

I would like to add new code in the Algorithms folder for Sequential Search under Python.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by CodeSadhu** [comment]
@akhileshsantoshwar What search algorithms do you want added? Also, are you accepting multiple contributors? If so, I would like to contribute.

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @CodeSadhu 

Happy Coding

**Comment by CodeSadhu** [comment]
@codePerfectPlus Thanks for assigning this to me! Where do I add this script file (in Python -> Algorithms -> Searching Algorithms or Python -> Algorithms -> Searching Algorithms -> Sequential Search -> script.py)?

**Comment by sourabmaity** [comment]
> * [x]  Assigning issue to @CodeSadhu
> 
> Happy Coding

why not me?

**Comment by codeperfectplus** [comment]
@SOURAB-BAPPA You already assigned to some issues.

**Comment by Pinak-coder** [comment]
@codePerfectPlus ,
 Please assign me for the task..

**Comment by nikhilgubbi** [comment]
I would like to take up this issue

**Comment by CodeSadhu** [comment]
@codePerfectPlus I've made a PR. Please review😊

**Comment by CodeSadhu** [comment]
@codePerfectPlus My PR has been labelled invalid. Why is that so?

**Comment by codeperfectplus** [comment]
@CodeSadhu Please create a pr again and linting your code with flake8.
