### ISSUE TITLE
Longest Common Subsequence | Dynamic Prpgramming | C++

### ISSUE THREAD

**Issue by SAY-droid427** [Py-Contributors/AlgorithmsAndDataStructure#119]
## **`Title`** -
Longest Common Subsequence in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SAY-droid427** [comment]
I want to add code in C++ to implement the longest common subsequence.Please assign this issue to me

**Comment by CodeSadhu** [comment]
@SAY-droid427 
 I'd like to take this up. To be clear, I just have to upload a c++ file with my solution in it, right?

**Comment by codeperfectplus** [comment]
@SAY-droid427 Add your c++ to Dynamic programming folder with proper documentation

- [x] Issue assigned to @CodeSadhu

**Comment by akhil-maker** [comment]
@SAY-droid427 
I would like to work on this issue #119 . Please assign it to me. 
I will code the implementation of longest common subsequence in C++ language.

**Comment by CodeSadhu** [comment]
@codePerfectPlus  Thanks! Working on it now!

**Comment by SAY-droid427** [comment]
Hey! I have opened a pull request to add the C++ code for longest common subsequence

**Comment by SAY-droid427** [comment]
It had been assigned to someone else although I wanted to add the code. So is my pull request invalid?

**Comment by SAY-droid427** [comment]
Since I wanted to contribute to this repository, I have also added the code for longest common subsequence in three sequences.Please do consider my pull request.

**Comment by javim-h** [comment]
Can I implement it on Python?

**Comment by codeperfectplus** [comment]
@CodeSadhu Sorry I have not seen that issue was created by @SAY-droid427 .

Assigning to @SAY-droid427

**Comment by SAY-droid427** [comment]
Thank you! I have made the pull request. Kindly review my code.Feedback on improving PR would be welcome.

**Comment by SSKale1** [comment]
@SAY-droid427 The Previous PR for LCS has been merged closing this issue.
