### ISSUE TITLE
Implement Queue in Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#12]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Implement Queue in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by SanskarGupta2207** [comment]
Kindly, assign me this task.

**Comment by ryanvarghese** [comment]
Sir, I would love to work on this. Can you please assign this task to me?

**Comment by codeperfectplus** [comment]
- [x] Assigning the task to @ryanvarghese 

Please make sure to give a star to the repo.

**Comment by ryanvarghese** [comment]
Okay will do that.

**Comment by ryanvarghese** [comment]
> * [x]  Assigning the task to @ryanvarghese
> 
> Please make sure to give a star to the repo.

I am doing this as a part of hacktober2020 so will it be fine if I send the pull request on October 1st?

**Comment by aman2457** [comment]
Hey @codePerfectPlus brother can you Assign this to me...

**Comment by codeperfectplus** [comment]
@aman2457 task is already assigned, You can check for other issues or create your own issue if something is missing in the repo.

Happy Coding
