### ISSUE TITLE
Ant colony optimization for traveling salesman problem | meta-heuristic Optimization | Python

### ISSUE THREAD

**Issue by hacky1997** [Py-Contributors/AlgorithmsAndDataStructure#124]
### Type of Issue -
meta-heuristic Optimization

Please add/delete options that are not relevant.

- [X] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [X] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by keivalya** [comment]
I want to take this issue.

**Comment by shubham5351** [comment]
@keivalya you can work on this issue.

**Comment by sujata13** [comment]
I want to contribute to this repository

**Comment by codeperfectplus** [comment]
@sujata13 why not, please check README and Contributing guidelines.
ISSUE and PR will be open from tomorrow.

Happy Coding
