### ISSUE TITLE
Unbounded Knapsack - Rod Cutting Problem | Dynamic Programming | Java

### ISSUE THREAD

**Issue by Ishita-0112** [Py-Contributors/AlgorithmsAndDataStructure#127]
## **`Unbounded Knapsack - Rod Cutting Problem - Dynamic Programming `** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vvekparmar** [comment]
can i work on this issue?

**Comment by Ishita-0112** [comment]
I wish to contribute to this issue created by me. If you would kindly assign me. Thanks.

**Comment by vvekparmar** [comment]
You said I will contribute to this repository right?
