### ISSUE TITLE
Particle Swarm Optimization Parallel and Sequential Implementation | Heuristic  | Python

### ISSUE THREAD

**Issue by jayitsaha** [Py-Contributors/AlgorithmsAndDataStructure#128]
## **`Particle Swarm Optimization`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by jayitsaha** [comment]
Can I Kindly work on this issue.

**Comment by HIMANSHU3107** [comment]
I'd love to work on this issue.

**Comment by codeperfectplus** [comment]
you can create new issues and PRs from Monday.

Happy Coding
