### ISSUE TITLE
Get Nth Element from Beginning or Last in a LinkList | Linklist | Python

### ISSUE THREAD

**Issue by aman2457** [Py-Contributors/AlgorithmsAndDataStructure#129]
## **`Nth Element`** -

**I want to add two functions in the Linklist python. the function is to get Nth Node from the beginning and another function is to get Nth node from the Last.** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3
Assign it to Me.
Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by vvekparmar** [comment]
can i work on this issue. Please assign these issue to me.

**Comment by sejalshri** [comment]
@aman2457 i would like to work on this issue. please assign ,it would be my first contribution to the repository.

**Comment by aman2457** [comment]
hey @sejalshri i have opened this issue for myself . but no problem we can open more issue in this repository. happy coding (:+1:

**Comment by gargnityansh** [comment]
@aman2457, it's my pleasure to solve this issue. I would like to contribute in it.

**Comment by Deephacks619** [comment]
I wanna work on this problem. please assign the task to me.
