### ISSUE TITLE
Implement Stack in python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#13]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** -Implement Stack in python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by SanskarGupta2207** [comment]
Kindly, assign me this task.

**Comment by codeperfectplus** [comment]
- [x] @Smrt-Sanskar Assigning issue

Happy Coding,

**Comment by HimadriPathak** [comment]
can i do this

**Comment by adayush** [comment]
Please assign this task to me

**Comment by GhostUser** [comment]
I can implement stacks in a optimal way, pls assign

**Comment by SanskarGupta2207** [comment]
Hey guys,

I am facing problems with the linting errors. Hence, I have unassigned me. Anyone interested to try can comment.

**Comment by HimadriPathak** [comment]
can you plz assign me

**Comment by GhostUser** [comment]
Assign me, I'll implement using python.

**Comment by GhostUser** [comment]
Assign me I'll also add explanation

**Comment by codeperfectplus** [comment]
assigning based on message priority
