### ISSUE TITLE
Kruskal Algorithm for Greedy method| Greedy Algorithms | Python

### ISSUE THREAD

**Issue by vvekparmar** [Py-Contributors/AlgorithmsAndDataStructure#139]
This Issue is for kruskal Algorithm for Minimum Spanning Tree using Greedy Approach,

- [x] Adding New Code

- [x] Python

- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file
Happy Coding,

**Comment by sounik97** [comment]
Please assign this issue to me

**Comment by NickkRodriguez** [comment]
Please assign this issue to me ASAP. I will do this right now. @shubham5351 @codePerfectPlus
