### ISSUE TITLE
LeakyReLU,Softmax,BinaryStepFunction | deep learning | Python

### ISSUE THREAD

**Issue by gr8geek** [Py-Contributors/AlgorithmsAndDataStructure#140]
## **`Implementation of classes of LeakyReLU,Softmax,BinaryStepFunction `** -

**Add new functionality in deep learning library** -

### Addition of new code -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

Happy Coding,

**Comment by gr8geek** [comment]
I am working on this issue

**Comment by envictuz** [comment]
Can I help to make some algorithm in the deep learning directory ?

**Comment by codeperfectplus** [comment]
@evanezcent You are welcome to contribute. Create an issue what you want to change or Add. 
check guidelines for more information.

Happy Coding

**Comment by codeperfectplus** [comment]
@gr8geek Please make a PR again. we are following flake8 standards for Python code.
