### ISSUE TITLE
Minimum spanning tree | Data Structure and algorithm | C++

### ISSUE THREAD

**Issue by katariarajat** [Py-Contributors/AlgorithmsAndDataStructure#142]
## **`Title`** -

**what will change** -

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by theekrystallee** [comment]
i would like to be assigned to this pls

**Comment by katariarajat** [comment]
hey @theekrystallee i have opened this issue for myself . But we could create more issue in this repository :+1:
