### ISSUE TITLE
Knapsack Dynamic Programming | DS Algo | Python

### ISSUE THREAD

**Issue by vvekparmar** [Py-Contributors/AlgorithmsAndDataStructure#149]
0/1 Knapsack Problem using dynamic programming.

- [x] Adding New Code

- [x] Python

- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability

Happy Coding,

**Comment by Bijay555** [comment]
Can you assign this to me?

**Comment by Rahul30032** [comment]
Can you assign this to me if not yet assigned to anyone?

**Comment by aparharsh** [comment]
Can you assign to me, if not yet assigned?

**Comment by sandiproybalitha** [comment]
Hi @vvekparmar . This is an interesting DP problem . I am glad to say you that I'm very dedicated to DSA.Please give me a chance to check my knowledge by assigning me this issue.

**Comment by vvekparmar** [comment]
This issue for created for myself.

**Comment by TanuAgrawal123** [comment]
Can you assign it to me? As I have good knowledge of DSA using python

**Comment by ExpressHermes** [comment]
assigned to @vvekparmar based on the issue creation.
