### ISSUE TITLE
Create Data Strucutre and Algorithm issue

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#15]
Hey, Welcome.

Create issues for Data Structures and Algorithms.

- Some code is missing in C++
- Some code is missing in Python
- Improve Previous Code
- Improve Documentation( There is README.md in every type of algorithms, you can write some 2-3 lines of the type of specific algorithm present in a folder)

**Comment by AkshadK7** [comment]
I see that there aren't any Program implementations on C++ Searching Algorithms in your repo.

Can I be assigned this issue for a Hacktoberfest PR ?

P.S:  You can always check out my Dev skills through my Github profile :)

**Comment by swastikchugh** [comment]
Hey @codePerfectPlus, I would like to contribute to this.

**Comment by codeperfectplus** [comment]
@AkshadK7 @swastikchugh, Welcome for the contribution.
I have already assigned some task for the searching algorithm in Python/C++. If any algorithm is missing you can create an issue for that. Make sure that task is not assigned before making a new issue. 

Happy Coding,

**Comment by AkshadK7** [comment]
Sure !

**Comment by lostgirljourney** [comment]
I would like to contribute for documentation part.

**Comment by codeperfectplus** [comment]
@lostgirljourney 
Please make an issue for what you want to change in documentation. 
There is README.md in every section of the Algorithm.

You will see some good change in the main README.md too ( table of the implemented algorithm in the project).
It's an idea of @ExpressHermes (Maintainer).

Good Luck,
