### ISSUE TITLE
Linear search | SearchingAlgorithms | C++

### ISSUE THREAD

**Issue by shonali-ks** [Py-Contributors/AlgorithmsAndDataStructure#153]
## **`Title`** - Linear Search | SearchingAlgorithms

I would like to add new code in the Algorithms folder for SearchingAlgorithms under C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by probhav** [comment]
Hi. I'm interested. kindly assign me! Happy to contribute.

**Comment by sandiproybalitha** [comment]
Hi @shonali-ks , I'm interested in the data structure and algorithmic problem. As this is an algorithimic problem I felling proud by contributing in it ,please assign me this issue!

**Comment by yuktagopalani** [comment]
Please assign this to me.

**Comment by suraj0223** [comment]
@shonali-ks , I can do this in optimal way. Can I work on this issue. ?

**Comment by shibrahmachari** [comment]
Please assign me this issue

**Comment by mainak-debnath** [comment]
Please assign this to me.
