### ISSUE TITLE
Fibonacci_bottom_up | Dyanamic Programming| C++

### ISSUE THREAD

**Issue by ishi0301** [Py-Contributors/AlgorithmsAndDataStructure#160]
## **`Title`** -

**what will change** -

### Type of Issue -A dyanamic programming problem 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ishi0301** [comment]
Please assign me this issue.

**Comment by stuxnet-8** [comment]
Can I contribute to this issue?

**Comment by ganeshbhandarkar** [comment]
Assign it to me

**Comment by ishi0301** [comment]
@ganeshbhandarkar @stuxnet-8 I have created this issue for myself. Kindly make your own issue and make a PR.

**Comment by SSKale1** [comment]
PR Merged. Closing issue.
