### ISSUE TITLE
Binary Tree Pre-order Traversal | Data Structure| C++

### ISSUE THREAD

**Issue by ishi0301** [Py-Contributors/AlgorithmsAndDataStructure#162]
## **`Title`** -
Binary Tree Pre-order Traversal
**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ishi0301** [comment]
Please assign me this issue.

**Comment by prc98** [comment]
I would like to work on this. Please assign me this issue.

**Comment by pikachu28** [comment]
Please assign this issue to me

**Comment by shubham5351** [comment]
@ishi0301 you can work on this issue.

**Comment by ishi0301** [comment]
@shubham5351 okay. Thanks
