### ISSUE TITLE
Sudoku Solver| Other | C++

### ISSUE THREAD

**Issue by ishi0301** [Py-Contributors/AlgorithmsAndDataStructure#163]
## **`Title`** -
Sudoku Solver
**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ishi0301** [comment]
Please assign me this issue.

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @ishi0301

**Comment by SSKale1** [comment]
Closed PR.
