### ISSUE TITLE
Binary Tree and AVL Tree | Data Structure | Python

### ISSUE THREAD

**Issue by Priyansi** [Py-Contributors/AlgorithmsAndDataStructure#166]
## Add Tree Data Structure -

Add code for Binary and AVL Tree in Python.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Priyansi** [comment]
I can work on it ASAP.

**Comment by ExpressHermes** [comment]
@Priyansi The issue for Tree implementation already exists. Make a seperate issue for AVL if it doesn't already exists, make a seperate PR and wait for approval before pushing a commit.
