### ISSUE TITLE
Tower of Hanoi | Recursion | C++

### ISSUE THREAD

**Issue by shonali-ks** [Py-Contributors/AlgorithmsAndDataStructure#167]
## **`Title`** -Tower of Hanoi

I would like to add Tower of Hanoi in cpp

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shonali-ks** [comment]
I would like to contribute to this

**Comment by aansh-01** [comment]
i would like to do this problem in cpp
Kindly assign it to me

**Comment by shubham5351** [comment]
@shonali-ks you can work on this issue.

**Comment by chehak123** [comment]
i would like to work on this. kindly assign it to me

**Comment by SSKale1** [comment]
PR Merged. Closing issue.
