### ISSUE TITLE
Naive algorithm for Pattern Searching in Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#17]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Naive algorithm for Pattern Searching in Python

**what will change** - Create a Folder if doesn't exist. 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by mehanix** [comment]
Hello, I could do this for Hacktober if that's okay.

Thanks!

**Comment by codeperfectplus** [comment]
@mehanix Ya sure,

- [x] Issue assigned to @mehanix 

**Note** - Hacktober Valid PR will count from 1 October- 31 October.
Happy coding,

**Comment by Deephacks619** [comment]
Hello, I wanna work on this issue. Can I do it?

**Comment by mehanix** [comment]
Hello,

I submitted my pull request.

Let me know if there's anything i need to modify.

Thanks!
