### ISSUE TITLE
Kadane Algorithm | Dynamic Programming| CPP

### ISSUE THREAD

**Issue by dhruv-singhal-github** [Py-Contributors/AlgorithmsAndDataStructure#170]
## **`Kadane Algorithm`** -

**what will change** - Adds algorithm to find maximum sum contiguous subarray using Dynamic Programming

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by dhruv-singhal-github** [comment]
I would love to work on this

**Comment by agarwalBinay18** [comment]
Can I work on this issue?
