### ISSUE TITLE
Kadane's algorithm|Algorithm | C++

### ISSUE THREAD

**Issue by hardikharti** [Py-Contributors/AlgorithmsAndDataStructure#171]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by agarwalBinay18** [comment]
Can I work on this issue?

**Comment by fastboot** [comment]
Can I take this?

**Comment by SadeepNanda** [comment]
may i work on this issue??
