### ISSUE TITLE
Permutation of a string | Back-tracking | Cpp

### ISSUE THREAD

**Issue by reachpranjal** [Py-Contributors/AlgorithmsAndDataStructure#174]
## **`Title`** - Finding all possible permutations of a string

**what will change** -  adding a new code

### Type of Issue -  Adding code file under c++

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AhmedElsisy** [comment]
can you assign it to me?

**Comment by sourabmaity** [comment]
i want to solve this issue

**Comment by reachpranjal** [comment]
This is not a duplicate issue. Kindly check the C++ repo !
