### ISSUE TITLE
Naive algorithm | Pattern Searching | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#18]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Naive algorithm for Pattern Searching

**what will change** - Create a Folder if doesn't exist. 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x]  C++

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by akashpatil-219** [comment]
I would be glad to this task for Hacktoberfest.

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @akashpatil-219 

Happy Coding,
