### ISSUE TITLE
ReLU | Deep Learning | Python

### ISSUE THREAD

**Issue by envictuz** [Py-Contributors/AlgorithmsAndDataStructure#185]
## **`Implementation of ReLU`** -

**what will change** -

### Add new functionality in deep learning library -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Vrindagupta6828** [comment]
@evanezcent  please assign me this

**Comment by pikachu28** [comment]
please assign me this
