### ISSUE TITLE
Merge Sort | Sorting algorithms | C++

### ISSUE THREAD

**Issue by blackfly19** [Py-Contributors/AlgorithmsAndDataStructure#188]
## **`Merge Sort in C++`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by blackfly19** [comment]
Can you assign me this issue?

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by amankothari1908** [comment]
Hey there !! Can you assign me this one ?? I want to solve this !!!!!

**Comment by codeperfectplus** [comment]
Duplicate issue
