### ISSUE TITLE
Cycle Sort | Sorting algorithm | C++

### ISSUE THREAD

**Issue by blackfly19** [Py-Contributors/AlgorithmsAndDataStructure#191]
## **`Cycle sort algorithm`** -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by blackfly19** [comment]
Please assign me this issue.

**Comment by sourabmaity** [comment]
i want to solve this issue

**Comment by vedanttttt** [comment]
Can Assign this to me if possible .

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @blackfly19

**Comment by ExpressHermes** [comment]
Duplicate of #54

**Comment by blackfly19** [comment]
So should I close my pull request for this issue?

**Comment by blackfly19** [comment]
Closed the issue because it's a duplicate.
