### ISSUE TITLE
Shell Sort | Sorting Algorithms | C++

### ISSUE THREAD

**Issue by aniketsingh98571** [Py-Contributors/AlgorithmsAndDataStructure#196]
## Shell Sort

Adding Shell Sort in [C++](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/tree/master/C%2B%2B/Algorithms/SortingAlgorithms)

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by aniketsingh98571** [comment]
I would like to work on this issue in C++, please assign it to me. @

**Comment by aniketsingh98571** [comment]
or I can do it in python also

**Comment by aniketsingh98571** [comment]
> i want to solve it

you can go with python

**Comment by aniketsingh98571** [comment]
I am doing this in C++

**Comment by sourabmaity** [comment]
ok , but assign me first

**Comment by aniketsingh98571** [comment]
I am not a maintainer,I have just created it

**Comment by aniketsingh98571** [comment]
@codePerfectPlus Please assign it to me I want to work on it in c++

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @aniketsingh98571

**Comment by aniketsingh98571** [comment]
@codePerfectPlus Why you have not merged my PR?
