### ISSUE TITLE
Implementation on DAG | DS |Python

### ISSUE THREAD

**Issue by anushkrishnav** [Py-Contributors/AlgorithmsAndDataStructure#199]
## **`Implementation of Directed Acyclic Graph`** -

**what will change** -

### Type of Issue -
Adding a DS

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
Python
Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by h4rz** [comment]
@anushkrishnav, I would like to work on it. Please assign.

**Comment by HIMANSHU3107** [comment]
I'd love to work on this issue, kindly assign

**Comment by anushkrishnav** [comment]
I want to work on Python .

**Comment by anushkrishnav** [comment]
> I'd love to work on this issue, kindly assign

can you do it in c++

**Comment by uditascloud** [comment]
Please assign me.Thank you

**Comment by tdserapio** [comment]
Please assign me, thank you in advanced.

**Comment by codeperfectplus** [comment]
#426 issue solved
