### ISSUE TITLE
Insertion sort algorithm in C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#2]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Add insertion sort Algorithm in C++

**what will change** - 

**Assignees** - 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by SanskarGupta2207** [comment]
Kindly, assign me this task.

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @Smrt-Sanskar 

Happy Coding

**Comment by sourabhkumar45** [comment]
I would like to work on it.

**Comment by SSKale1** [comment]
PR Merged.
