### ISSUE TITLE
Stacks | DataStructure | C++

### ISSUE THREAD

**Issue by SSKale1** [Py-Contributors/AlgorithmsAndDataStructure#202]
## **`Adding Code showing internal functionality of Stacks`** -

**Code for making a Stack DataStructure** - To actually understand the working of stacks, it is important to implement it rather than using the STL. I will be adding the code, please assign me to this issue. So I can make the PR.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by hnishal** [comment]
can I get this issue?

**Comment by sherwin2000** [comment]
please can u give me this issue?

**Comment by sujata13** [comment]
@SSKale1  Can you please assign me this issue? I will like to contribute to this. Thanks

**Comment by SSKale1** [comment]
This issue has been Closed
