### ISSUE TITLE
A* Heuristic Search | Algorithm | Python

### ISSUE THREAD

**Issue by SristiDakshit** [Py-Contributors/AlgorithmsAndDataStructure#205]
## **`Title`** - A star heuristic search algorithm

**what will change** - Add code

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SristiDakshit** [comment]
I want to work on this issue, please assign it to me

**Comment by conjurer2306** [comment]
I'm really interested in contributing to this project. Kindly assign me a task.
