### ISSUE TITLE
Bit Masking Operations |  C++

### ISSUE THREAD

**Issue by ganeshbhandarkar** [Py-Contributors/AlgorithmsAndDataStructure#206]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ganeshbhandarkar** [comment]
I want to work on this please assign it to me.

**Comment by ganeshbhandarkar** [comment]
I have created pull request. please review it.

**Comment by GunjanMA** [comment]
I want to add some questions(topic: bit manipulation) and their solutions in c++.
Kindly assign the issue to me.

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.
