### ISSUE TITLE
Multiple Linear Regression | Machine Learning Algorithm | Python

### ISSUE THREAD

**Issue by SristiDakshit** [Py-Contributors/AlgorithmsAndDataStructure#207]
## **`Title`** - Multiple Linear Regression

**what will change** - Add Code

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SristiDakshit** [comment]
Please assign it to me

**Comment by pikachu28** [comment]
Please assign it to me

**Comment by abhisheks008** [comment]
please assign to me

**Comment by gadde5300** [comment]
Please assign it to me.

**Comment by ansh-lehri** [comment]
Please assign it to me.
