### ISSUE TITLE
Sudoku Solver using Backtracking Algorithm

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#21]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Sudoku Solver using Backtracking Algorithm

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by mukuakhilesh** [comment]
As I get, here the code of Sudoku Solving with Backtracking is to be implemented in both C++ and python.
@codePerfectPlus can you clarify that we just need to add the solution with and example in both language.
And can you assign this issue to me.

**Comment by codeperfectplus** [comment]
Welcome to Py-contributors,
yes, we have the issue to add sudoku solver using backtracking in Python and C++.

You want to solve it in python or C++

**Comment by mukuakhilesh** [comment]
I can do it in both Python and C++.

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @mukuakhilesh 

Happy Coding

**Comment by GhostUser** [comment]
pls assign i'll add a well written code

**Comment by mukuakhilesh** [comment]
I @GhostUser I have almost completed this part. You can open a new issue for any other algorithms which has not been added in repo or issues till now.
P.S. See in Dynamic Programming, many common algo has not been implemented till now.

**Comment by GhostUser** [comment]
@mukuakhilesh No issues, I'll do that

**Comment by mukuakhilesh** [comment]
@codePerfectPlus  can you confirm, I can already see a SudokuSolver code in python #113 . 

Also, one PR is open for C++ #260. But, this is in separate folder. Mine is for Backtracking folder-C++.
So, is the PR for this really needed ?

**Comment by codeperfectplus** [comment]
@mukuakhilesh 
you can create sudoku solver in c++ using backtracking.

**Comment by codeperfectplus** [comment]
leave the Python sudoku it's already done.
