### ISSUE TITLE
Disjoint Set Union | Data Structure | C++

### ISSUE THREAD

**Issue by VyomGarg47** [Py-Contributors/AlgorithmsAndDataStructure#214]
## **`Title`** - Implementation of Disjoint Set Union Data Structure and its use cases.

**what will change** -

### Type of Issue - Adding a Data Structure

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by VyomGarg47** [comment]
Can I work on this ?

**Comment by Ankitkumarjaiswal** [comment]
I want to work on this issue.

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.
