### ISSUE TITLE
N Queen Problem | Backtracking | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#22]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - N Queen Problem | Backtracking | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by gokulkannan7** [comment]
I would love to work on this sir

**Comment by gokulkannan7** [comment]
I would love to work on this, can u assign it to me?

**Comment by gokulkannan7** [comment]
since it is a part of hacktoberfest. should I put a PR in October?

**Comment by codeperfectplus** [comment]
- [x] Assigning the task to @gokulkannan7 

Happy Coding

**Comment by codeperfectplus** [comment]
Closing issue 
Reason- no PR and activity in a week. 

#446 
Issue assigned here
