### ISSUE TITLE
Two stacks in an array | Data structures | C++

### ISSUE THREAD

**Issue by shonali-ks** [Py-Contributors/AlgorithmsAndDataStructure#221]
## **`Title`** -Implementing two stacks in an array

I would like to implement two stacks in an array in Stack folder.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shonali-ks** [comment]
Can I contribute to this issue?

**Comment by shubham5351** [comment]
@shonali-ks you can work on this issue.

**Comment by adityasinghbaghel** [comment]
I would like to contribute .

**Comment by shubham5351** [comment]
I have merged this issue so I closed it work on new issue.
