### ISSUE TITLE
KMeans | MachineLearning | Python

### ISSUE THREAD

**Issue by blackfly19** [Py-Contributors/AlgorithmsAndDataStructure#226]
## **`KMeans algorithm`** -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by blackfly19** [comment]
Can you please assign me this issue.

**Comment by JulietaCaceres** [comment]
Can I do this?

**Comment by nikhilgubbi** [comment]
Please do Assign it to me. I can solve this

**Comment by pikachu28** [comment]
Please assign this to me. I can do it

**Comment by ExpressHermes** [comment]
assigned to @blackfly19
