### ISSUE TITLE
Improvements in Python Linked List

### ISSUE THREAD

**Issue by antoniouaa** [Py-Contributors/AlgorithmsAndDataStructure#23]
**Title** - Improvements in Python Linked List

**What will change** - Python Linked List implementation improvements will add and/or amend code to make it better, more idiomatic and decrease time complexity of some operations

### Type of Issue -

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation

### Programming Language

- [x] Python

If possible I'd like to be assigned this task for Hacktoberfest.

**Comment by ExpressHermes** [comment]
I can work on this.

**Comment by codeperfectplus** [comment]
- [x] assigning the issue based on comment priority to @antoniouaa

**Comment by antoniouaa** [comment]
My PR was merged so I'm just gonna close this.
