### ISSUE TITLE
Longest Palindromic Subsequence | Dynamic Programming | C++

### ISSUE THREAD

**Issue by chiru-cd** [Py-Contributors/AlgorithmsAndDataStructure#231]
## **`Title`** - Longest Palindromic Subsequence

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by chiru-cd** [comment]
I would like to work on this issue.

**Comment by Jayshah6699** [comment]
@SSKale1 I have worked on this issue kindly assign this issue to me

**Comment by vedanttttt** [comment]
Assign this to me please, i know how to do it .

**Comment by soumakpoddar** [comment]
I would like to work on it......

**Comment by Khalleud** [comment]
i would like to work on this problem

**Comment by chiru-cd** [comment]
@ExpressHermes @SSKale1 This issue is yet unassigned. Please let me know if there is a problem with this issue.

**Comment by SSKale1** [comment]
@chiru-cd will be assigned to the task by issue preference. Sorry for the delay :)

**Comment by shubham5351** [comment]
I have merged your code work on another issue.
