### ISSUE TITLE
Z Algorithm | Pattern Searching | C++

### ISSUE THREAD

**Issue by BalajiG2000** [Py-Contributors/AlgorithmsAndDataStructure#233]
## Z algorithm (Linear time pattern searching Algorithm)-

This algorithm finds all occurrences of a pattern in a text in linear time. Let length of text be n and of pattern be m, then total time taken is O(m + n) with linear space complexity. Now we can see that both time and space complexity is same as KMP algorithm but this algorithm is Simpler to understand.

### Type of Issue -
        Coding and Documentation .The code should be readable , commented well, documented clearly .

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by UtkarshGoelUT** [comment]
please assign this to me.

**Comment by ExpressHermes** [comment]
assigned to @UtkarshGoelUT
