### ISSUE TITLE
Kosaraju Algorithm | Graph | C++

### ISSUE THREAD

**Issue by UtkarshGoelUT** [Py-Contributors/AlgorithmsAndDataStructure#234]
## **`Title`** - Add Kosaraju Algorithm in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by UtkarshGoelUT** [comment]
I would like to work on it.

**Comment by uditascloud** [comment]
please assign it to me. thank you

**Comment by vinaypathak07** [comment]
I would like to work on this.

**Comment by SSKale1** [comment]
- [x]  @UtkarshGoelUT is assigned to this Issue, for issue creation.
