### ISSUE TITLE
Heap Sort | Soting Algorithm | Python

### ISSUE THREAD

**Issue by Halix267** [Py-Contributors/AlgorithmsAndDataStructure#236]
## **`HEAP SORT`** -

**what will change** - heap_sort

### Type of Issue -
- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Halix267** [comment]
I want to wrk on this issue . Plzz assign it me

**Comment by sourabmaity** [comment]
i want to do it plz assign me

**Comment by uditascloud** [comment]
please assign it to me. thank you

**Comment by Halix267** [comment]
@SOURAB-BAPPA @uditascloud .Plzz create your own issue.

**Comment by shaswatsingh19** [comment]
I can do this in python can you assign it to me

**Comment by ExpressHermes** [comment]
Duplicate. Already exists #6
