### ISSUE TITLE
Maximum Area of Histogram | Stack | C++

### ISSUE THREAD

**Issue by mukundkedia** [Py-Contributors/AlgorithmsAndDataStructure#239]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by mukundkedia** [comment]
I would like to contribute.

**Comment by yashkumar0707** [comment]
I would like to contribute.

**Comment by YA12SHYAM** [comment]
I would like to contribute to this as my first PR, Please assign it

**Comment by codeperfectplus** [comment]
you can create new issues and PRs from Monday.

Happy Coding
