### ISSUE TITLE
N Queen Problem | BacktrackingAlgorithms | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#24]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Implementation of N Queen Problem | BacktrackingAlgorithms | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request

:star2: Star it 

:fork_and_knife:Fork it

:handshake: Contribute to it!

Happy Coding,

**Comment by hot9cups** [comment]
Hi, I'd like to be assigned to this!

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @hot9cups
