### ISSUE TITLE
Heap Sort | Sorting algorithm | Python  issue 125

### ISSUE THREAD

**Issue by shaswatsingh19** [Py-Contributors/AlgorithmsAndDataStructure#240]
### Type of Issue -

Please add/delete options that are not relevant.

- [tick] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [tick] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by shaswatsingh19** [comment]
I would like to work on it in python , can you assign it to me

**Comment by ExpressHermes** [comment]
Duplicate of #6
