### ISSUE TITLE
Fix README.md of Python Algorithm

### ISSUE THREAD

**Issue by SristiDakshit** [Py-Contributors/AlgorithmsAndDataStructure#245]
## **`Title`** - Fix README.md 

**what will change** -Fix the README.md of Algorithms under Python

### Type of Issue -
- [] Adding New Code
- [] Improving Code
- [x] Improving Documentation
- [] Bug Fix

### Programming Language
- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by pradumio** [comment]
I can do this, If you can brief me the details?

**Comment by SristiDakshit** [comment]
I'm sorry, I didn't clarify. I opened this issue as I wanted to work on it for hacktoberfest.

**Comment by dheerajghosh007** [comment]
Assign this issue to me,

**Comment by ExpressHermes** [comment]
@SDakshit Can you elaborate on the changes that you plan to do?

**Comment by SristiDakshit** [comment]
@ExpressHermes  Right now, the same algorithms are mentioned twice-once in bullets and once normally. That should definitely be fixed. And I'd also like to add a brief description about each algorithm , that will help new comers understand what it's all about.

**Comment by ANKITAKHAN** [comment]
Can you assign this issue to me?

**Comment by dheerajghosh007** [comment]
Description of various algorithms are not given and the information is not systematic so i want to change those

**Comment by ExpressHermes** [comment]
assigning to you. @SDakshit based on issue creation.

**Comment by Natasha1305** [comment]
Can this issue be assigned to me?

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by ExpressHermes** [comment]
Issue solved!
