### ISSUE TITLE
Karp’s algorithm | Minimum mean weight | Python

### ISSUE THREAD

**Issue by thisavijit** [Py-Contributors/AlgorithmsAndDataStructure#246]
Given a directed and strongly connected graph with non-negative edge weights. We define the mean weight of a cycle as the summation of all the edge weights of the cycle divided by the no. of edges. Our task is to find the minimum mean weight among all the directed cycles of the graph.

**Comment by thisavijit** [comment]
I would like to work on this

**Comment by ExpressHermes** [comment]
@adavijit. I think this issue already exists at #41.

**Comment by codeperfectplus** [comment]
#41 issue close, person unassigned himself. @adavijit  you can create a PR tomorrow.
Please pull the latest change from the upstream branch
