### ISSUE TITLE
Binary Search | SearchingAlgorithms | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#25]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Binary Search | SearchingAlgorithms | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request

:star2: Star it 

:fork_and_knife:Fork it

:handshake: Contribute to it!

Happy Coding,

**Comment by ghost** [comment]
I would like to work on this. Please assign me for this issue.

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @tusharsbauskar

**Comment by vaibhav-jain18** [comment]
I would like to work on this.

**Comment by vaibhav-jain18** [comment]
I want to improve its implementation
