### ISSUE TITLE
LinkedList | Data Structures| Python

### ISSUE THREAD

**Issue by agasheaditya** [Py-Contributors/AlgorithmsAndDataStructure#250]
## **`Square the linked list elements and return in sorted order`** -

**what will change** - Input will be the list of sorted integers and output will be the sorted squared linked list. 

### Type of Issue - 

- [x] Adding New Code 9Enhancement/feature addition)

### Programming Language : 

- [x] Python

* Example code

`class Node(object):

    def __init__(self,d,n=None):
        self.data = d
        self.next_node = n

    def get_next(self):
        return self.next_node
    
    def set_next(self,n):
        self.next_node = n
    
    def get_data(self):
        return self.data
    
    def set_data(self,d):
        self.data = d

    def has_next(self):
        if self.get_next() is None:
            return False
        return True

    def to_string(self):
        return ("Node Val : "+str(self.data))

class LinkedList(object):
    def __init__(self,r=None):
        self.root = r
        self.size = 0
        
    def get_size(self):
        return self.size
    
    def add(self,d):
        new_node = Node(d,self.root)
        self.root = new_node
        self.size += 1

    def print_list(self):
        print("Printing a linked list...")
        if self.root is None:
            return
        this_node = self.root
        print(this_node.to_string())
        while this_node.has_next():
            this_node = this_node.get_next()
            print(this_node.to_string())
        
    def remove(self,d):
        this_node = self.root
        prev_node = None

        while this_node is not None:
            if this_node.get_data() == d:
                if prev_node is not None:
                    prev_node.set_next(this_node.get_next())
                else:
                    self.root = this_node.get_next()
                self.size -= 1
                return True
            else:
                prev_node = this_node
                this_node = this_node.get_next()
        return False
    
    def find(self,d):
        this_node = self.root
        while this_node is not None :
            if this_node.get_data() == d:
                return d
            elif this_node.get_next() == None:
                return False
            else:
                this_node = this_node.get_next()`

**Comment by shikhar-sharma1703** [comment]
I would like to work on this issue.

**Comment by akshat235** [comment]
Please assign this to me.

**Comment by khush31** [comment]
It could be great if you could asign this issue to me.

**Comment by agasheaditya** [comment]
@shikhar-sharma1703 go-ahead and work on the same.
