### ISSUE TITLE
Kadane's Algorithm | Maximum Contiguous Subarray sum| Python

### ISSUE THREAD

**Issue by GSNCodes** [Py-Contributors/AlgorithmsAndDataStructure#253]
## Kadane's Algorithm
**what will change** -
It is used to find the maximum contiguous subarray sum. The code will be added in python.

### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by GSNCodes** [comment]
@codePerfectPlus  please assign this issue to me :)

**Comment by UtkarshGoelUT** [comment]
please assign it to me.

**Comment by GSNCodes** [comment]
@UtkarshGoelUT  Sorry, I created this to work on it. You could work on something else 👍

**Comment by shaswatsingh19** [comment]
I would like to work on it in python , can you assign it to me

**Comment by shaonakundu** [comment]
hey @GSNCodes will you assign me this issue? I know Kadane's algo in python so please assign me this task

**Comment by MdAkdas** [comment]
i can do this in cpp. @GSNCodes assign me this.

**Comment by codeperfectplus** [comment]
@GSNCodes  you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding
