### ISSUE TITLE
Heaps and Priority Queues | Data structure | C++

### ISSUE THREAD

**Issue by V41SH** [Py-Contributors/AlgorithmsAndDataStructure#255]
## Heaps/Priority Queues

Implement priority queue data structure with heaps in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by UtkarshGoelUT** [comment]
please assign it to me.

**Comment by V41SH** [comment]
I would like to be assigned this issue.

**Comment by sherwin2000** [comment]
please assign it to me

**Comment by sherwin2000** [comment]
i am a 5 star coder on codechef,

**Comment by shaswatsingh19** [comment]
I can do this in python can you assign it to me

**Comment by ExpressHermes** [comment]
assigned to @V41SH based on the issue creation.

**Comment by V41SH** [comment]
@ExpressHermes I have opened a pr for this issue (linked it as well).

**Comment by ExpressHermes** [comment]
@V41SH We will try to merge it asap

**Comment by SSKale1** [comment]
PR Merged
