### ISSUE TITLE
Binary Search | SearchingAlgorithms | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#26]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Binary Search | SearchingAlgorithms | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request

:star2: Star it 

:fork_and_knife:Fork it

:handshake: Contribute to it!

Happy Coding,

**Comment by hot9cups** [comment]
I would like to take this up :)

**Comment by codeperfectplus** [comment]
- [x] Issue Assigned to @hot9cups

**Comment by HimadriPathak** [comment]
can i do this

**Comment by hot9cups** [comment]
@HimadriPathak This issue has already been assigned. However, you can still have a look at other unassigned issues, or make an issue of your own to add code or fix broken code :)

**Comment by ExpressHermes** [comment]
@codePerfectPlus @hot9cups This issue already exists at #9. @codePerfectPlus, I think this issue should be closed.
