### ISSUE TITLE
Floyd's Cycle Finding algorithm| Linked List| Python

### ISSUE THREAD

**Issue by Anay121** [Py-Contributors/AlgorithmsAndDataStructure#265]
## **Adding Floyd's Cycle finding algorithm for a Linked List** -

**Adding code for performing Floyd's cycle detection algorithm in a linked list written in python, as well the linked list class taken from previous implementations** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sanskarvijpuria** [comment]
I want to take this issue

**Comment by Anay121** [comment]
Oh, sorry, I meant to write
Im opening this issue because I'm working on it.

**Comment by shaonakundu** [comment]
Can i contribute on this issue I have knowledge of how to use Floyd's cycle to detect loops in linked list, so please will you assign me?

**Comment by ExpressHermes** [comment]
assigned to @Anay121
