### ISSUE TITLE
Stack Implementation using Linked List | Data Structure| C++

### ISSUE THREAD

**Issue by adityasinghbaghel** [Py-Contributors/AlgorithmsAndDataStructure#267]
## **`Implement Stack using Singly Linked List`** -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

Happy Coding,

**Comment by adityasinghbaghel** [comment]
Hey ! please assign this issue to me .

**Comment by jakansha2001** [comment]
Can you assign this issue to me?

**Comment by minichhabra** [comment]
Please assign this issue to me.

**Comment by Badkul77** [comment]
Please Assign it to me , i have a optimal solution

**Comment by adityasinghbaghel** [comment]
> Can you assign this issue to me?

Create Your own issue😊

**Comment by shubham5351** [comment]
duplicate issue no - #70
