### ISSUE TITLE
Negative Likelihood Logarithmic loss - Deep Learning

### ISSUE THREAD

**Issue by hot9cups** [Py-Contributors/AlgorithmsAndDataStructure#27]
I'd like to add the NLL loss to the deep learning directory's loss functions.

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @hot9cups
