### ISSUE TITLE
Merge Sort | Algorithm | C++

### ISSUE THREAD

**Issue by pranavbharadwaj007** [Py-Contributors/AlgorithmsAndDataStructure#271]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++
### Self Check 
- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by mainak-debnath** [comment]
Please this issue to me

**Comment by drishtipeshwani** [comment]
Would like to contribute can you please assign

**Comment by saiharsha-22** [comment]
@pranavbharadwaj007 I would like to contribute can you please assign me this task.

**Comment by SSKale1** [comment]
@pranavbharadwaj007 Making Commits before being assigned will term it as Invalid. We'll be closing your PR.

**Comment by Heisenberg-737** [comment]
@pranavbharadwaj007 I would like to contribute to this.
Please assign me this task.
