### ISSUE TITLE
Pancake Sorting | Sorting Algorithms | C

### ISSUE THREAD

**Issue by kashika3101** [Py-Contributors/AlgorithmsAndDataStructure#274]
## **`Pancake Sorting Algorithm`** -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by kashika3101** [comment]
Please assign me this issue.

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by parjanyaacoder** [comment]
I would like to work on this issue.

**Comment by ExpressHermes** [comment]
Assigned to @kashika3101
