### ISSUE TITLE
Array Insertion and Deletion | Data Structure | C++

### ISSUE THREAD

**Issue by wjeevika** [Py-Contributors/AlgorithmsAndDataStructure#277]
## **`Title`** - Array Insertion and Deletion

**what will change** - Inserting and deleting in a given array

### Type of Issue - Insertion and deletion in an array, in the front, end, or at any position

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by wjeevika** [comment]
May I please request you to allow me to work on this issue?
@codePerfectPlus, please assign me this issue.

**Comment by ExpressHermes** [comment]
@MeeeCoder This is a very unnecessary issue. All the array algorithms(insertion, and deletion) should be a single issue. Please avoid making extra issues for something which can be done in one issue.

**Comment by wjeevika** [comment]
@ExpressHermes I have made the required changes, now insertion and deletion is a single issue.
So, now can you please assign this issue to me?

**Comment by ExpressHermes** [comment]
@MeeeCoder this issue is very trivial. Please avoid working on this issue. It will be closed after review by @codePerfectPlus
