### ISSUE TITLE
Centroid of a Tree | Algorithms | C++

### ISSUE THREAD

**Issue by VyomGarg47** [Py-Contributors/AlgorithmsAndDataStructure#278]
## **`Title`** - Find Centroid of a Given Tree

Centroid of a Tree is a node which if removed from the tree would split it into a ‘forest’, such that any tree in the forest would have at most half the number of vertices in the original tree.

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.
- [x] Adding New Code

### Programming Language
Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by VyomGarg47** [comment]
Please assign this to me.

**Comment by shubham5351** [comment]
As this issue is merged so I closed it.
