### ISSUE TITLE
Array Deletion | Data Structure | C++

### ISSUE THREAD

**Issue by wjeevika** [Py-Contributors/AlgorithmsAndDataStructure#279]
## **`Title`** - Array Deletion

**what will change** - Deleting elements from  a given array

### Type of Issue - Deleting elements from the front, end, or at any position in an array

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by wjeevika** [comment]
@codePerfectPlus, Please allow me to work on this issue.

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by ExpressHermes** [comment]
This issue is unnecessary. Closing it. You can include this issue in #277

**Comment by wjeevika** [comment]
> This issue is unnecessary. Closing it. You can include this issue in #277

Included this issue in #277
