### ISSUE TITLE
ReLU and TanH class implementations

### ISSUE THREAD

**Issue by hot9cups** [Py-Contributors/AlgorithmsAndDataStructure#28]
I'd like to complete the TanH and ReLU class implementations in the Deep Learning directory

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by codeperfectplus** [comment]
- [x]  Assigning the issue to @hot9cups

**Comment by hot9cups** [comment]
- [x]

**Comment by hot9cups** [comment]
- [x] task assigning to @hot9cups
