### ISSUE TITLE
Heap Sort | Sorting Algorithm | Python

### ISSUE THREAD

**Issue by akhileshsantoshwar** [Py-Contributors/AlgorithmsAndDataStructure#286]
## **`Title`** - Heap Sort | Sorting Algorithm | Python
I want to work on this issue.

**what will change** - Adding new program for Heap Sort in Python

### Type of Issue - 

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

**Assignees** - @akhileshsantoshwar

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue, please assign me this issue.

**Comment by OfficialNMN** [comment]
can i work on this issue??

**Comment by akhileshsantoshwar** [comment]
@OfficialNMN , I have already started working on it.

**Comment by ExpressHermes** [comment]
Duplicate issue. Already exists. #6. @akhileshsantoshwar Please refer to the contribution guide before creating any issue.
