### ISSUE TITLE
Shell Sort | Sorting Algorithm | Python

### ISSUE THREAD

**Issue by akhileshsantoshwar** [Py-Contributors/AlgorithmsAndDataStructure#289]
## **`Title`** - Shell Sort | Sorting Algorithm | Python

**what will change** - Adding new program for Shell Sort | Sorting Algorithm in Python

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

**Assignees** - @akhileshsantoshwar

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue, please assign me this issue.

**Comment by sparshs413** [comment]
Please assign me this task!!

**Comment by akhileshsantoshwar** [comment]
@sparshs413 , I have already started working on this issue.

**Comment by sparshs413** [comment]
@akhileshsantoshwar you were working on other issues as well let me work on it

**Comment by akhileshsantoshwar** [comment]
@sparshs413 you can work on it in different language. Because I already started working on this.

**Comment by ExpressHermes** [comment]
assigned to @akhileshsantoshwar based on the issue creation
