### ISSUE TITLE
Selection Sort | SortingAlgorithms | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#29]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Selection sort algorithm implementation in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request

:star2: Star it 

:fork_and_knife:Fork it

:handshake: Contribute to it!

Happy Coding,

**Comment by shravani05** [comment]
Can I work on this issue? @codePerfectPlus

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @shravani05 

HappyCoding,

**Comment by HimadriPathak** [comment]
can i do this issue

**Comment by codeperfectplus** [comment]
@HimadriPathak This issue is already assigned to someone. check other issue or create your own issue and make sure that doesn't exist.
Happy Coding

**Comment by shravani05** [comment]
@codePerfectPlus  I have made the PR with the necessary requirements, please review it.

**Comment by shravani05** [comment]
I have made the PR #395 with all the flake8 checks passed, please review it. @codePerfectPlus
