### ISSUE TITLE
Counting Sort | Sorting Algorithms | Python

### ISSUE THREAD

**Issue by akhileshsantoshwar** [Py-Contributors/AlgorithmsAndDataStructure#294]
## **`Title`** - Counting Sort | Sorting Algorithms | Python

**what will change** - Adding new program for Counting Sort | Sorting Algorithms in Python.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

**Assignees** - @akhileshsantoshwar

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue, please assign me this issue.

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by akhileshsantoshwar** [comment]
@SOURAB-BAPPA I have already started working on this, you can solve it in different language

**Comment by codeperfectplus** [comment]
@akhileshsantoshwar   you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding

**Comment by DilshanDeAlmeida** [comment]
Hi @akhileshsantoshwar can you assign me to this. I have the working implemented in python.!!
