### ISSUE TITLE
Doubly Linked List | Data Structure | Python

### ISSUE THREAD

**Issue by akhileshsantoshwar** [Py-Contributors/AlgorithmsAndDataStructure#297]
## **`Title`** - Doubly Linked List | Data Structure | Python

**what will change** - Adding new program for Doubly Linked List | Data Structure in Python

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

**Assignees** - @akhileshsantoshwar

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue, please assign me this issue.

**Comment by RahulMaurya9** [comment]
I want to work on this issue. I'll follow all rule.

**Comment by pikachu28** [comment]
I want to work on this issue, please assign me this issue.

**Comment by shubham5351** [comment]
@akhileshsantoshwar you can work on this issue.
