### ISSUE TITLE
Binary Search | Searching | C++

### ISSUE THREAD

**Issue by sparshs413** [Py-Contributors/AlgorithmsAndDataStructure#298]
## **`Title`** -

**what will change** - Adding new Program for Binary Search in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sparshs413** [comment]
I am working on this!!!

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by satwik-chowdary** [comment]
Can i work on this

**Comment by sparshs413** [comment]
@satwik-chowdary @SOURAB-BAPPA I have already started working on this!!

**Comment by ExpressHermes** [comment]
Duplicate of #25
