### ISSUE TITLE
Diameter of a n-ary tree | Algorithm | C++

### ISSUE THREAD

**Issue by aru233** [Py-Contributors/AlgorithmsAndDataStructure#299]
### Type of Issue -
Adding New Code

### Programming Language
C++

### Self Check 
- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by aru233** [comment]
Hi @codePerfectPlus , can I work on this issue?
I don't see this concept and would help to have it compiled here.

**Comment by satwik-chowdary** [comment]
Can I do this

**Comment by ExpressHermes** [comment]
Assigned to @aru233
