### ISSUE TITLE
Merge sort implementation in C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#3]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Merge sort implementation in C++

**what will change** -

**Assignees** - @d2Anubis 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by d2Anubis** [comment]
I would like to work on this.

**Comment by dikshantmali** [comment]
@codePerfectPlus assign this task to me please

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @d2Anubis

**Comment by d2Anubis** [comment]
Done and created a PR.

**Comment by d2Anubis** [comment]
Done and created a PR :)

**Comment by SSKale1** [comment]
PR Merged Closing issue.
