### ISSUE TITLE
Selection Sort | SortingAlgorithms | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#30]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Selection sort algorithm in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request

:star2: Star it 

:fork_and_knife:Fork it

:handshake: Contribute to it!

Happy Coding,

**Comment by anandhakrishnanaji** [comment]
Can I work on this issue?

**Comment by codeperfectplus** [comment]
- [x] Assigning the task to @anandhakrishnanaji 

Happy Coding,

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.
