### ISSUE TITLE
Strassen's Algorithm for Matrix Multiplication | DivideAndConquer | Python

### ISSUE THREAD

**Issue by shikhar-sharma1703** [Py-Contributors/AlgorithmsAndDataStructure#300]
## **`Strassen's Algorithm for Matrix Multiplication`** -

**what will change** -
A file will be added for this algorithm.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shikhar-sharma1703** [comment]
Would you please assign me this issue?

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by rajinderpalsingh2001** [comment]
I want to Solve this Problem, can you please Assign it to me.

**Comment by ExpressHermes** [comment]
Assigned to @shikhar-sharma1703
