### ISSUE TITLE
Algorithm name | Category | Language

### ISSUE THREAD

**Issue by minichhabra** [Py-Contributors/AlgorithmsAndDataStructure#303]
### Issue #267 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] C++

Happy Coding,

**Comment by murattishkul** [comment]
Please kindly assign this to me!

**Comment by Ajay0511** [comment]
Please assign this to me in Python.

**Comment by ExpressHermes** [comment]
Duplicate
