### ISSUE TITLE
A* Search Algorithm| Algorithms  | Python

### ISSUE THREAD

**Issue by abhinavprkash** [Py-Contributors/AlgorithmsAndDataStructure#312]
### Type of Issue - Good first issue

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Manavi18** [comment]
I can contribute. Can it be assigned to me?

**Comment by abhisht51** [comment]
Can you assign this to me ??

**Comment by ExpressHermes** [comment]
Check #205. It's a duplicate issue.
