### ISSUE TITLE
Segment Tree | Data Structures | Python

### ISSUE THREAD

**Issue by chrismilson** [Py-Contributors/AlgorithmsAndDataStructure#314]
# **Segment Tree**

The segment tree ([wikipedia](https://en.wikipedia.org/wiki/Segment_tree)) is an important data structure. 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by chrismilson** [comment]
I would like to be assigned to this.

**Comment by Shishir198** [comment]
Can I be assigned for this issue please

**Comment by ExpressHermes** [comment]
Assigned to @chrismilson
