### ISSUE TITLE
Palindrome Partitioning | Dynamic Programming | C++

### ISSUE THREAD

**Issue by deekshalala** [Py-Contributors/AlgorithmsAndDataStructure#315]
## **Palindrome Partitioning** -

**We can solve the problem of palindrome partitioning by Dynamic Programming** 

### Type of Issue - Dynamic Programming

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by codetravellearn** [comment]
i would love to contribute

**Comment by deekshalala** [comment]
Please assign this to me

**Comment by Khalleud** [comment]
I would like to work on this problem

**Comment by codeperfectplus** [comment]
@deekshalala   you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding

**Comment by shubham5351** [comment]
I have merged this issue, Please work on new issue.
