### ISSUE TITLE
The Knight's tour problem | BacktrackingAlgorithm | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#32]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - The knight is placed on the first block of an empty board and, moving according to the rules of chess, must visit each square exactly once.
 
**Refernce** - https://www.geeksforgeeks.org/the-knights-tour-problem-backtracking-1/

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Bijay555** [comment]
Can you assign this to me?

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @Bijay555 
:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
