### ISSUE TITLE
Boolean Parenthesization Problem | Dynamic Programming | Python

### ISSUE THREAD

**Issue by div-bargali** [Py-Contributors/AlgorithmsAndDataStructure#322]
## **`Boolean Parenthesization Problem`** 

Given a boolean expression with symbols ( 'T' and 'F' ) and the binary operators ( "^", "|" , "&" ), count the number of ways we can parenthesize the expression so that the value of expression evaluates to true.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by div-bargali** [comment]
I would like to be assigned this issue.

**Comment by pikachu28** [comment]
Please assign this issue to me : )

**Comment by codeperfectplus** [comment]
@div-bargali   you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding
