### ISSUE TITLE
Anagrams | Data Structure | Python

### ISSUE THREAD

**Issue by ArunKumar-25** [Py-Contributors/AlgorithmsAndDataStructure#328]
## **`Anagrams Problem`** -

**Checking if two words are anagrams** -

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ArunKumar-25** [comment]
I would like to be assigned this issue.

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by sourabmaity** [comment]
please assign me for this work

**Comment by megabyte98** [comment]
can you please assign this issue to me .

**Comment by Pinak-coder** [comment]
Please assign me for this as i have a short and sweet code for the same..

**Comment by utsavk28** [comment]
please assign me this , i have already written a clean code

**Comment by ExpressHermes** [comment]
@ArunKumar-25 make sure this implementation is not already being worked upon. Any PR made to the issue before being approved and assigned will be closed.

**Comment by MananTyagi** [comment]
please assign this issue to me, I  will try to write algorithm in Time complexity of O(n) or even faster, I will make sure that I will use like ..counter function rather than simply sorting, or using ord()

**Comment by MananTyagi** [comment]
although i will provide with proper documentation for understanding and explanation of algorithm

**Comment by ArunKumar-25** [comment]
@ExpressHermes I have checked that no one is working on it that's why I craeted this issue . Please assign it to me, I Will provide proper explanation with algorithm.

**Comment by ArunKumar-25** [comment]
@ExpressHermes I have checked that no one is working on it that's why I created this issue. Please assign it  to me I will provide proper explanation with algorithm.

**Comment by ExpressHermes** [comment]
assigned to @ArunKumar-25 based on the issue creation.

**Comment by ExpressHermes** [comment]
@MananTyagi You can take any other issue or suggest a new issue if it not already being worked on.

**Comment by MananTyagi** [comment]
> @MananTyagi You can take any other issue or suggest a new issue if it not already being worked on.

ok sir @ExpressHermes 
thanks
