### ISSUE TITLE
The Knight's tour problem | backtracking | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#33]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - The Knight's tour problem | backtracking | C++
**Reference** -https://www.geeksforgeeks.org/the-knights-tour-problem-backtracking-1/
**what will change** - 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by utkarshbajaj** [comment]
I'd like to do this, please assign

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @utkarshbajaj

**Comment by SSKale1** [comment]
PR merged, closing issue.
