### ISSUE TITLE
Kruskal Algorithm | Algorithm  | Python

### ISSUE THREAD

**Issue by anushkrishnav** [Py-Contributors/AlgorithmsAndDataStructure#330]
## **`Kruskal Algorithm`** -

**what will change** -
New file
### Type of Issue -
New algorithm
Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
Python,C++
Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by anushkrishnav** [comment]
Assign me Python please

**Comment by sourabmaity** [comment]
i want to solve it please assign me

**Comment by ayushjaipuriyar** [comment]
Sir I would like to contribute for this algorithm in c++

**Comment by utsavk28** [comment]
please assign this to me , i have already wrote the code for it

**Comment by srivathsa729** [comment]
please assign this to me

**Comment by shubham5351** [comment]
As this issue is already present issue no - #139
