### ISSUE TITLE
Fix README.md for C++ Searching Algorithms

### ISSUE THREAD

**Issue by srivathsa729** [Py-Contributors/AlgorithmsAndDataStructure#343]
## **`Title`** - Fix README.md

**what will change** -
Fix the readme of searching Algorithms in c++/Algorithms/SearchingAlgorithms
### Type of Issue -

Please add/delete options that are not relevant.

- [] Adding New Code
- [] Improving Code
- [x] Improving Documentation
- [] Bug Fix

### Programming Language
- [x] C++
- [] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by srivathsa729** [comment]
@ExpressHermes Please assign this issue to me

**Comment by sharmashantanu** [comment]
Please assign this issue to me

**Comment by ExpressHermes** [comment]
@srivathsa729 Please elaborate on what type of fixes/changes you will be making. What will improve with your changes?

**Comment by srivathsa729** [comment]
@ExpressHermes Readme of Searching Algorithms is empty, I would like to add definition of searching algorithm and types of  searching algorithms used for different data structures etc.
