### ISSUE TITLE
Merge Sort & Quick Sort | Sorting | C++

### ISSUE THREAD

**Issue by jainaayush01** [Py-Contributors/AlgorithmsAndDataStructure#344]
## **`Add 2 More Sorting Algorithms`** -

**Merge Sort and Quick Sort Algorithms** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by jainaayush01** [comment]
Please assign this to me

**Comment by prabhdeepsingh3499** [comment]
Please assign this to me.

**Comment by pbisen** [comment]
I would love to work on this.

**Comment by PranavDani** [comment]
I could work on this issue

**Comment by snehagupta-4** [comment]
Please assign this to me
