### ISSUE TITLE
Binary Exponentiation | Algorithms | C++

### ISSUE THREAD

**Issue by clueless100** [Py-Contributors/AlgorithmsAndDataStructure#346]
## **`Title`** -

**Binary Exponentiation - Number Theory (Calculating powers in O(log n))** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by clueless100** [comment]
Would appreciate it if I was assigned to this.

**Comment by anushkrishnav** [comment]
I can work on Python

**Comment by ExpressHermes** [comment]
assigned to @clueless100 based on the issue creation

**Comment by anushkrishnav** [comment]
> assigned to @clueless100 based on the issue creation

Yeh I will work on python

**Comment by ExpressHermes** [comment]
@anushkrishnav Make sure to read the contribution file. If you want to work on this in Python, create a separate issue and wait for its approval from maintainers. Any PR made without approval/assignment will be closed and labeled `invalid`.

**Comment by karthikeyanrathore** [comment]
Can I work on this issue. I can implement Binary Exponentiation in c++

**Comment by SSKale1** [comment]
PR has been merged.
