### ISSUE TITLE
Segmented sieve | Primes algorithm |C++

### ISSUE THREAD

**Issue by devesh-anand** [Py-Contributors/AlgorithmsAndDataStructure#350]
## **`Segmented sieve`** -

**Will add a C++ code to calculate primes between number A and B in optimized time** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by devesh-anand** [comment]
@ExpressHermes Can you assign me this one?

**Comment by sbhavya18** [comment]
kindly assign me this.
