### ISSUE TITLE
Priority Queues | Data structure | Python

### ISSUE THREAD

**Issue by div-bargali** [Py-Contributors/AlgorithmsAndDataStructure#352]
## **`Priority Queues`** 

Implement priority queue data structure with queue in Python.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it

**Comment by div-bargali** [comment]
@ExpressHermes  I would like to be assigned this issue.

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by ExpressHermes** [comment]
Assigned to @div-bargali

**Comment by div-bargali** [comment]
@ExpressHermes Please review #600 .
Thank you.

**Comment by ExpressHermes** [comment]
Fixed in #600
