### ISSUE TITLE
Pancake sort | Sorting algorithm | python

### ISSUE THREAD

**Issue by Rj-coder-iitian** [Py-Contributors/AlgorithmsAndDataStructure#355]
I want to implement this in python, please assign this to me.

**Comment by Rj-coder-iitian** [comment]
@ExpressHermes Please assign this to me, I would like to work on it.

**Comment by ExpressHermes** [comment]
@Rj-coder-iitian Link the PR with this issue otherwise it will not be accepted

**Comment by prasenjitghose36** [comment]
is this open now

**Comment by Rj-coder-iitian** [comment]
> @Rj-coder-iitian Link the PR with this issue otherwise it will not be accepted

how to link the pr with the issue? I am new to this, please guide me.

**Comment by ExpressHermes** [comment]
Mention the issue number( #355) in PR template.

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java and C++. Please assign.
