### ISSUE TITLE
Power using recursion | Recursion Algo | Cpp

### ISSUE THREAD

**Issue by MdAkdas** [Py-Contributors/AlgorithmsAndDataStructure#356]
## **`Title`** -
Program to Compute Power Using Recursion.
**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by uditswaroopa09** [comment]
I would like to work on it

**Comment by MdAkdas** [comment]
@ExpressHermes i want to work on this issue. please assign me this.

**Comment by ExpressHermes** [comment]
@MdAkdas assigned to you based on the issue creation

**Comment by shubham5351** [comment]
I have closed this issue as it is merged.
