### ISSUE TITLE
Interpolation Search| Searching Algorithm| C++

### ISSUE THREAD

**Issue by srivathsa729** [Py-Contributors/AlgorithmsAndDataStructure#358]
### Type of Issue - Interpolation Search Algorithm is Missing

- [x] Add New Code for algorithm

### Programming Language
- [x] C++

### Self Check 

- [x] Ask for issue assignment before making Pull Request.
- [x] Add your file in the proper folder
- [x] `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
I would like to work on it.

**Comment by srivathsa729** [comment]
@codePerfectPlus please assign this issue to me
I would implement the Algorithm

**Comment by ExpressHermes** [comment]
assigned to @srivathsa729
