### ISSUE TITLE
Minimum coin change problem | Dynamic Programming | cpp

### ISSUE THREAD

**Issue by MdAkdas** [Py-Contributors/AlgorithmsAndDataStructure#359]
## **`Title`** -
Given a value V, if we want to make change for V cents, and we have infinite supply of each of C = { C1, C2, .. , Cm} valued coins, what is the minimum number of coins to make the change?

**what will change** -
New program

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by MdAkdas** [comment]
@ExpressHermes i would like to work on this issue. Please assign me this.

**Comment by aedorado** [comment]
@ExpressHermes I would like to work on this issue. Can you please assign me?

**Comment by Lutir** [comment]
@ExpressHermes can I work on this?

**Comment by akshaykale17** [comment]
Happy to contribute to this issue! Can you please assign me this Issue!?

**Comment by hydra-sketch** [comment]
can I get a chance to contribute to this?

**Comment by SanskarGupta2207** [comment]
I am a competitive programmer with 2 years of experience. But I am new to open source and looking for issues involving problem solving in C++. Kindly, assign me this task.
