### ISSUE TITLE
Prediction by SVM | Machine Learning Algorithms | Python

### ISSUE THREAD

**Issue by Sankalpagrawal** [Py-Contributors/AlgorithmsAndDataStructure#360]
## **`Title`** - Implement RBF kernel and prediction functions from scratch by SVM in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Sankalpagrawal** [comment]
I want to take up this issue

**Comment by dhirendrachoudhary** [comment]
i want to take this issue

**Comment by gadde5300** [comment]
Please assign it to me

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by codeperfectplus** [comment]
@Sankalpagrawal   you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding
