### ISSUE TITLE
Visualisation for various different sorting algorithms in Python, cool animations | Algorithms  | Python

### ISSUE THREAD

**Issue by gr8geek** [Py-Contributors/AlgorithmsAndDataStructure#364]
## **`Visualisation for various different sorting algorithms in Python`** -

**I plan to add a GUI tool to create a visualizer to visualize algorithms in python** -

### Addition of a new GUI along with animation 
I got this inspiration from 3 blue one brown youtube channel

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Python

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gr8geek** [comment]
I am working on this issue

**Comment by sourabmaity** [comment]
what is the names of that shorting algos?

**Comment by codePerfectPlus** [comment]
@gr8geek Thanks for making the issue,
We are implementing the algorithm only in CLI. 
your issue looking interesting, instead of making PR here. you can start a new repository for implementing the algorithm with GUI.

**Comment by codeperfectplus** [comment]
@gr8geek Thanks for making the issue,
We are implementing the algorithm only in CLI. 
your issue looking interesting, instead of making PR here. you can start a new repository for implementing the algorithm with GUI.

Please also share some details which framework you will use for GUI. Are you using manim library for that.

**Comment by gr8geek** [comment]
@codePerfectPlus I am using pygame library

**Comment by codeperfectplus** [comment]
Your ideas of implementing GUI on sorting algorithm is good. But we are implementing only algorithms. I will let you know when we will start any project related to GUI for algorithms.
Happy Coding,
