### ISSUE TITLE
Decision Tree algorithm | Machine learning | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#37]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR. **Add Proper Documentation, Problem statement, any refernce link**

**Title** - Decision tree algorithm implementation in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @codePerfectPlus

**Comment by V41SH** [comment]
I would like to be assigned this issue.

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.
