### ISSUE TITLE
Longest Increasing Subsequence | Dynamic Programming | C++

### ISSUE THREAD

**Issue by mukuakhilesh** [Py-Contributors/AlgorithmsAndDataStructure#371]
## **`Longest Increasing Subsequence Implementation in C++`** -

**what will change** - Addition of new script for Longest Increasing Subsequence in C++.

### Type of Issue -

- [X] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shubham5351** [comment]
PR Merged.
