### ISSUE TITLE
Knapsack Problem | Dynamic Programming | Python

### ISSUE THREAD

**Issue by saswatamcode** [Py-Contributors/AlgorithmsAndDataStructure#374]
## **`Add`**-

**Need to add Knapsack problem in Dynamic Programming in Python**

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vaibhav-jain18** [comment]
I would like to work on this.

**Comment by dhirendrachoudhary** [comment]
I would like to add Knapsack code

**Comment by Lutir** [comment]
I would like to add a solution!

**Comment by Sameera-Aryasomayajula** [comment]
I would like to add the Knapsack solution in C++

**Comment by gadde5300** [comment]
Please assign it to me

**Comment by JupeOwl** [comment]
I'd like to work on this!

**Comment by shubham5351** [comment]
Issue no - #149
