### ISSUE TITLE
InsertionSort | Sorting Algorithms | C++

### ISSUE THREAD

**Issue by sayashraaj** [Py-Contributors/AlgorithmsAndDataStructure#375]
## **`Title`** - InsertionSort algorithm implementation in C++

**what will change** - Addition of new script for InsertionSort algorithm in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve it please

**Comment by SSKale1** [comment]
Duplicate Issue already exits at #2 .Closing Issue.
