### ISSUE TITLE
K-Nearest Neighbours | Machine learning | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#38]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR. **Add Proper Documentation, Problem statement, any reference link**

**Title** - K-nearest Neighbours algorithms implementation in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Halix267** [comment]
@codePerfectPlus I want to contribute to this issue. Can you assign this issue to me.

**Comment by codeperfectplus** [comment]
- [x]  task assigning to @Halix267

**Comment by hot9cups** [comment]
[x] task assigning to

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.
