### ISSUE TITLE
Binary Search | Divide and Conquer | C++

### ISSUE THREAD

**Issue by vaibhav-jain18** [Py-Contributors/AlgorithmsAndDataStructure#380]
## **`Adding Binary Search`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vaibhav-jain18** [comment]
I would like to work on this issue.

**Comment by sourabmaity** [comment]
I would like to work on this issue.

**Comment by ExpressHermes** [comment]
Duplicate of #25
