### ISSUE TITLE
Image processing for deep learning module  | DeepLearning | Python

### ISSUE THREAD

**Issue by gr8geek** [Py-Contributors/AlgorithmsAndDataStructure#385]
## **`A class in deep learning module for handling RGB color images`** -

**The module will have the capability to perform operation like 
Grey Scaling color images
Performing thresholding and Binarization on images ** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to work on this issue

**Comment by gr8geek** [comment]
@SOURAB-BAPPA 
Please feel free to work on the issue
Create A file called Binarization.py and perform thresholding operation

**Comment by gr8geek** [comment]
I am working on Greyscale algorithim conversion

**Comment by pikachu28** [comment]
Please assign this issue to me : )

**Comment by geoffgeorgein** [comment]
I am currently working on computer vision projects. Please assign me this. I can do something about it.

**Comment by codeperfectplus** [comment]
@gr8geek   you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding
