### ISSUE TITLE
Jump Search | Searching Algorithms | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#39]
**Title** - Jump Search algorithm implementation in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- One Change in one Pull Request
- Ask for issue assignment before making PR
- Add file in the proper folder
- clean code and documentation for better readability
- add title and what program will do first in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shubham5351** [comment]
I would like to work on this issue

**Comment by heisastark** [comment]
Hey! Can I please work on this?

**Comment by shubham5351** [comment]
Can I work on this issue

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @shubham5351 

Happy Coding

**Comment by codeperfectplus** [comment]
@shubham5351  Are you still working on It?

**Comment by shubham5351** [comment]
I'm not working on this issue right now you can assign it to someone else.

**Comment by SupraJ1** [comment]
Can I work on this?

**Comment by shubham5351** [comment]
@SupraJ1 you can work on this issue.

**Comment by SauravBaba** [comment]
@codePerfectPlus please assign to me
