### ISSUE TITLE
Euler Methods For Ordinary Differential Equations | Algorithms | Python

### ISSUE THREAD

**Issue by brtymn** [Py-Contributors/AlgorithmsAndDataStructure#391]
## Euler Methods For Ordinary Differential Equations

Euler methods for solving ordinary differential equations will be added.

### New Script

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by brtymn** [comment]
I want to take this on!

**Comment by ExpressHermes** [comment]
@brtymn assigned to you

**Comment by dianas11xx** [comment]
Hey! I would like to take this issue since it's still open!
