### ISSUE TITLE
Rod Cutting Problem | Dynamic Programming | C++

### ISSUE THREAD

**Issue by Lutir** [Py-Contributors/AlgorithmsAndDataStructure#392]
## **`Rod Cutting Problem`** -

**Adding a DP approach for Rod-Cutting problem** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Lutir** [comment]
Can I be assigned to this problem?

**Comment by gpk2000** [comment]
Hi is this resolved? If not I would like to contribute to it

**Comment by codeperfectplus** [comment]
Best of luck @gpk2000
