### ISSUE TITLE
Topological Sort | Sorting Algorithm | C++

### ISSUE THREAD

**Issue by NoobSolver** [Py-Contributors/AlgorithmsAndDataStructure#393]
## **`Adding Topological Sorting Algorithm`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve this issue

**Comment by NoobSolver** [comment]
I can do it with better approach.

**Comment by NoobSolver** [comment]
@SSKale1 Opening this issue for topological sort.Please assign it to me.

**Comment by SSKale1** [comment]
Sorry @NoobSolver This is a duplicate issue #220 . Will have to close this issue.
