### ISSUE TITLE
QuickSort Algorithm implementation in C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#4]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - QuickSort Algorithm implementation in C++

**what will change** -

**Assignees** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by d2Anubis** [comment]
I would like to work on this.

**Comment by codeperfectplus** [comment]
- [x] @d2Anubis Issue assigned

**Comment by d2Anubis** [comment]
Done and created a pull request.

**Comment by d2Anubis** [comment]
Let me know if you want any changes before merging.

**Comment by SSKale1** [comment]
Closing PR.
