### ISSUE TITLE
KMP Algorithm | Pattern Searching | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#40]
## **`Title`** - KMP Algorithm Implementation in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vamsyvrishank** [comment]
Hey @codePerfectPlus ! Can i please work on this?

**Comment by codeperfectplus** [comment]
- [x] Assigning the issue to @VamsyVrishank 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by codeperfectplus** [comment]
This issue is open for assignment

**Comment by SupraJ1** [comment]
Can I work on this?

**Comment by ExpressHermes** [comment]
Assigned to @SupraJ1

**Comment by codeperfectplus** [comment]
@SupraJ1 We haven't received your PR yet. Are you still working on It?
