### ISSUE TITLE
Binary to Gray Code Conversion | Algebra/Number_System | Python

### ISSUE THREAD

**Issue by utsavk28** [Py-Contributors/AlgorithmsAndDataStructure#400]
## **`Binary to Gray Code Conversion`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by utsavk28** [comment]
Please Assign this problem to me

**Comment by sourabmaity** [comment]
i want to solve this problem

**Comment by rishabh-28** [comment]
Please assign this to me.

**Comment by ExpressHermes** [comment]
assigned to @utsavk28
