### ISSUE TITLE
Rabin-Karp Algorithm | Pattern Searching | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#41]
## **`Title`** - Rabin-Karp Algorithm for Pattern Searching

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by heisastark** [comment]
Hey! Can you please assign me this? @codePerfectPlus

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @heisastark 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by heisastark** [comment]
@codePerfectPlus PR's will be counted from 1st Oct, right?

**Comment by codeperfectplus** [comment]
yeah @heisastark
