### ISSUE TITLE
Subsequences using Recursion | Recursion | cpp

### ISSUE THREAD

**Issue by MdAkdas** [Py-Contributors/AlgorithmsAndDataStructure#415]
## **`Title`** -
Generating all possible Subsequences using Recursion
**what will change** -
new  program.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by MdAkdas** [comment]
@codePerfectPlus @ExpressHermes  i want to work on this issue.

**Comment by shriyaMadan** [comment]
I would like to solve this issue.

**Comment by MdAkdas** [comment]
Given a string print its all subsequence.
ex:- for string abc , it's subsequence are 
abc
ab
ac
a
bc
b
c
@ExpressHermes

**Comment by pikachu28** [comment]
Please assign this issue to me : )

**Comment by sbhavya18** [comment]
kindly assign this issue to me.
