### ISSUE TITLE
BFS | Algorithms | C++

### ISSUE THREAD

**Issue by karthikeyanrathore** [Py-Contributors/AlgorithmsAndDataStructure#416]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by bagladivyang03** [comment]
Hey pls assign me this :)

**Comment by karthikeyanrathore** [comment]
Can I work on this issue ?
Created this issue because there is not BFS algorithm in the repo.

**Comment by ayushjaipuriyar** [comment]
can i get assigned for this for either of the two language ?

**Comment by shubham5351** [comment]
Duplicate issue no - #349.
