### ISSUE TITLE
Support Vector Machine | Machine Learning | Python

### ISSUE THREAD

**Issue by ugetshivam** [Py-Contributors/AlgorithmsAndDataStructure#417]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by pikachu28** [comment]
Please assign this to me!!

**Comment by Suyash-Batham** [comment]
Please assign this issue to me...

**Comment by Suyash-Batham** [comment]
I've started working on this issue. Please assign me this : ) @ugetshivam

**Comment by ugetshivam** [comment]
@Suyash-Batham I have made this issue so that I could work on it. :)

**Comment by codeperfectplus** [comment]
@  you can create new issues and PRs from tomorrow. 

- Make sure to use Flake8 standard If your coding in Python.

Happy Coding
