### ISSUE TITLE
Rabin Karp | String Matching algorithm | C++

### ISSUE THREAD

**Issue by blackfly19** [Py-Contributors/AlgorithmsAndDataStructure#419]
## **`Rabin karp algorithm** -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.

**Comment by SSKale1** [comment]
@blackfly19 Create Another PR adding your code to the correct directory. You had added to Python DIR.

**Comment by blackfly19** [comment]
I am really sorry. I didn't realise I put my code in the wrong directory. I have created another PR with my file in the right directory.

**Comment by SSKale1** [comment]
Okay, Its alright

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.
