### ISSUE TITLE
GCD and LCM | Math | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#42]
## **`Title`** - Implement GCD and LCM in Python

**what will change** - Create a folder `maths` if it doesn't exist and Put your code inside it.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vamsyvrishank** [comment]
Can i please work on this? @codePerfectPlus

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @VamsyVrishank 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by codeperfectplus** [comment]
You can create pr from tomorrow. Best of Luck @Suyash-Batham 

Happy Coding

**Comment by shubham5351** [comment]
PR Merged.
