### ISSUE TITLE
Binary Search | Searching Algorithms | C++

### ISSUE THREAD

**Issue by vaibhav-jain18** [Py-Contributors/AlgorithmsAndDataStructure#421]
## **`Improving Binary Search implementation`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [] Adding New Code
- [x] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vaibhav-jain18** [comment]
I want to work on this issue

**Comment by ExpressHermes** [comment]
PR merged
