### ISSUE TITLE
Binary Search | Searching | c++

### ISSUE THREAD

**Issue by Priyansh2001here** [Py-Contributors/AlgorithmsAndDataStructure#425]
## **`Add comments for better understanding`** -

**what will change** -

### Type of Issue -Improvement

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [ ] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Priyansh2001here** [comment]
please let me work on it

**Comment by ExpressHermes** [comment]
@codePerfectPlus @Priyansh2001here Binary Search issue already exists. I think it's a duplicate issue

**Comment by Priyansh2001here** [comment]
You can still merge the pull request with more doc and typing

**Comment by Shyamashrita** [comment]
Hey i want to work on this issue.

**Comment by priya1799** [comment]
I would like to work on this issue! Can you please assign this issue to me?

**Comment by SSKale1** [comment]
Closing this issue now.
