### ISSUE TITLE
Trie | Data Structures | Python

### ISSUE THREAD

**Issue by ayushjaipuriyar** [Py-Contributors/AlgorithmsAndDataStructure#428]
## **`Trie`** 

**what will change** -

### Type of Issue - 

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ayushjaipuriyar** [comment]
i would like to contribute to this repository by adding the program for trie in python

**Comment by pikachu28** [comment]
Please assign this to me : )

**Comment by ayushjaipuriyar** [comment]
@binpatel31 This issue hasn't been assigned to anyone so please remove your pull request, and follow the contribution.md

**Comment by ayushjaipuriyar** [comment]
Also I raised this issue for myself, to get self-assigned it wasn't supposed to be assigned to anyone else

**Comment by hot9cups** [comment]
@ayushjaipuriyar you may go ahead and work on this.
