### ISSUE TITLE
sieve of eratosthenes | Maths | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#43]
## **`Title`** - Sieve of Eratosthenes in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Manoj13-coder** [comment]
Assign this to me

**Comment by UtkarshGoelUT** [comment]
I would like to work on it.

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @UtkarshGoelUT 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by Subham142** [comment]
im new to open-source ....so just wanna ask since it is assigined so...can't contribute to this bug now......or can i??


if i'm allowed then plzz allow me also

**Comment by codeperfectplus** [comment]
Issue assigned to someone else.

Assigning a task to 2 people will create conflict with the file.
After Issue submission, you can make an issue if you want to improve it.
like:- Reducing the time complexity 

@shubham5351

**Comment by SSKale1** [comment]
Merged PR. Closing Issue.
