### ISSUE TITLE
Edit Distance | Dynamic Programming | C++

### ISSUE THREAD

**Issue by nikunjagarwal321** [Py-Contributors/AlgorithmsAndDataStructure#431]
## **`Edit Distance Problem`** -

**Add cpp solution for the edit distance problem
where one has to convert string1 to string2 with minimum number of edits** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by nikunjagarwal321** [comment]
Can I please work on this issue?

**Comment by shushriya6998** [comment]
Can I work on this? I'll be using C++. Thanks!

**Comment by SeverX** [comment]
Could you probably assign this issue to me?

**Comment by ExpressHermes** [comment]
Assigned to @nikunjagarwal321
