### ISSUE TITLE
Bellman-Ford Algorithm | Path Finding Algorithms | Python

### ISSUE THREAD

**Issue by carol975** [Py-Contributors/AlgorithmsAndDataStructure#434]
## **`Adding Bellman-Ford Algorithm for Python`** -

**what will change** - new directory named PathFindingAlgorithms. Within that directory a new file named BellmanFord.py containing an implementation of the Bellman-Ford shortest path algorithm.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by snehagupta-4** [comment]
Hey, I'd like to work on this issue. Please assign it to me

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by carol975** [comment]
Actually me too, I want to be assigned to work on this issue. :). I'm already working on this issue on the side. Will submit a pr if I get assigned.

**Comment by rahulsunil2** [comment]
I've great experience in writing [clean and readable code](https://github.com/rahulsunil2/CProgramming/blob/master/GraphTheory/layCables.c), so I would like to work on this issue.
Can you please assign it to me?
