### ISSUE TITLE
Maximize Expression | Dynamic Programming | Python

### ISSUE THREAD

**Issue by srivastavaayu** [Py-Contributors/AlgorithmsAndDataStructure#435]
## **`Title`** - Maximize an expression

**what will change** - A new file MaximizeExpression.py will be added in /Python/Algorithms/DynamicProgramming

### Type of Issue - Addition of an algorithm

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by srivastavaayu** [comment]
I would like to work on this issue.

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.
