### ISSUE TITLE
Articulation points | Graph Algorithms | C++

### ISSUE THREAD

**Issue by thepritam** [Py-Contributors/AlgorithmsAndDataStructure#437]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by thepritam** [comment]
Can I please work on this ?

**Comment by shubham5351** [comment]
duplicate issue no - #228
