### ISSUE TITLE
Graph Algorithm | Topological Sort using DFS & BFS Algo

### ISSUE THREAD

**Issue by Jappan07** [Py-Contributors/AlgorithmsAndDataStructure#438]
This is to add Topological sort algorithm which has a lot of applications in computer science. For example: The dependencies in OS are sorted using this algorithm. It is important to understand this algo and hence I want to add it to the repo. May I?

### Programming Language
- [x] C++

**Comment by nikhil121101** [comment]
I am in;)

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by Jappan07** [comment]
Actually I am on it.

**Comment by SSKale1** [comment]
Duplicate issue #220 . We'll have to close this issue.
