### ISSUE TITLE
Sieve of Eratosthenes | Maths | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#44]
## **`Title`** - sieve of eratosthenes implementation in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
I would like to work on this. Please assign me.

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @tusharsbauskar 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding
