### ISSUE TITLE
Stairs Problem | Dynamic Programming | C++

### ISSUE THREAD

**Issue by hardikharti** [Py-Contributors/AlgorithmsAndDataStructure#442]
## **`Stairs Problem`** -

**Adding New code ** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by kishanpatel22** [comment]
May I work on this issue ?

**Comment by SeverX** [comment]
Could you assign this issue to me?
