### ISSUE TITLE
KARATSUBA | Divide And Conquer | C++

### ISSUE THREAD

**Issue by KISLAYA-SRI** [Py-Contributors/AlgorithmsAndDataStructure#444]
## **`KARATSUBA ALGORITHM`** -

**Adding new Code** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sparsh-99** [comment]
@KISLAYA-SRI , I would love to contribute in. Please assign this to me!!

**Comment by shubham5351** [comment]
@KISLAYA-SRI you can work on this issue.

**Comment by KISLAYA-SRI** [comment]
I have compled the work. Please review and merge the PR.

**Comment by codeperfectplus** [comment]
you haven't mentioned the issue number is your pull request.
