### ISSUE TITLE
Exponential Search | Algorithm | python

### ISSUE THREAD

**Issue by MananTyagi** [Py-Contributors/AlgorithmsAndDataStructure#445]
## **`Exponential Search in python`** -

**In python directory /algorithms / search algorithms it will implement exponential search algorithm in python ** -

### Type of Issue - 
- [x] Adding New Code

### Programming Language
- [x] Python

### Self Check 
- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by MananTyagi** [comment]
I would like to work on this issue

**Comment by rahulsunil2** [comment]
I've great experience in writing [clean and readable code](https://github.com/rahulsunil2/CProgramming/blob/master/GraphTheory/layCables.c), so I would like to work on this issue.
Can you please assign it to me?

**Comment by Sameera-Aryasomayajula** [comment]
I would like to contribute to this issue. I can work on the C++ implementation.

**Comment by MananTyagi** [comment]
@Sameera-Aryasomayajula there is python label on it.

**Comment by shubham5351** [comment]
duplicate issue no - #100
