### ISSUE TITLE
N Queens | BackTrackingAlgorithms | Python

### ISSUE THREAD

**Issue by DavidBanda** [Py-Contributors/AlgorithmsAndDataStructure#446]
## **`N Queens Problem`** -

**Add a new algorithm** -

### Type of Issue -

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python
- [ ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by DavidBanda** [comment]
I've contributed to other algorithm repositories and I'd like to work on this one.

**Comment by Amrita211** [comment]
Can you please assign this task to me. I would like to work on this !

**Comment by codeperfectplus** [comment]
@DavidBanda Thanks for making your issue. please use flake8 for python code
