### ISSUE TITLE
Sieve of Atkin | Maths | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#45]
## **`Title`** - Sieve of Atkin in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Manoj13-coder** [comment]
i like to do it may i?

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @Manoj13-coder

**Comment by Manoj13-coder** [comment]
May i send you PR on 1st of October please . so that this contribution will
also be counted for hacktober contest .

**Comment by codeperfectplus** [comment]
Ya Sure Make your PR on 1st October.

**Comment by Manoj13-coder** [comment]
Thanks alot

**Comment by codeperfectplus** [comment]
@Manoj13-coder We haven't received your PR yet. Are you still working on It?

**Comment by Manoj13-coder** [comment]
sorry for my delay i will send you pr in 5 minutes
