### ISSUE TITLE
Gnome Sort | SortingAlgorithms | Python

### ISSUE THREAD

**Issue by aaravm4** [Py-Contributors/AlgorithmsAndDataStructure#452]
## **`Add Gnome Sort Algorithm`** -

**what will change** - In the directory `Python/Algorithms/SortingAlgorithms` there'll be a new file `GnomeSort.py`. This file contains the implementation for Gnome Sort.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by aaravm4** [comment]
Can I please be assigned this for Hacktoberfest.

**Comment by ashutosh321607** [comment]
I can implement it in c++. please assign it to me for c++.

**Comment by shubham5351** [comment]
@aaravm4 you can work on this issue.

**Comment by theja-vanka** [comment]
Hi please assign me this issue.
