### ISSUE TITLE
Convert Decimal Value to Any Base | Maths | Python

### ISSUE THREAD

**Issue by sourabmaity** [Py-Contributors/AlgorithmsAndDataStructure#455]
## **`Title`** -Decimal to N base conversion 

**what will change** -
In the directory 'Python/Algorithms/' create your own folder and place your program inside that folder.
Take input from user - Decimal value , Base value( In which he/she want to convert)
Example - Input : 125 , 7
              Output : Equivalent of 125 in base 7 is  236
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
I am already working on this issue please assign it to me

**Comment by ke-utkarsh** [comment]
Please assign this to me, i can write neat and detailed code to convert to any base

**Comment by codeperfectplus** [comment]
please put your code in maths folder

**Comment by sourabmaity** [comment]
issue solved
