### ISSUE TITLE
Simple Polygon Area | Geometry | Python

### ISSUE THREAD

**Issue by viagostini** [Py-Contributors/AlgorithmsAndDataStructure#456]
## **`Calculate Area of Simple Polygons`** -

**I will add code for calculating area of simple polygon in O(N) time in Python** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by viagostini** [comment]
Hey, can you please assign this one to me? :smile:

**Comment by ke-utkarsh** [comment]
Please assign this issue to me i can code area of n sided polygon in O(n) in python as well as C++

**Comment by Nirali0029** [comment]
I will surely like to complete this task using python

**Comment by riddhi-jain** [comment]
please assign me the issue.

**Comment by DeathcallXD** [comment]
can u plz assign this to me in c++ @viagostini
