### ISSUE TITLE
Fenwick Tree | Data Structures | C++

### ISSUE THREAD

**Issue by viagostini** [Py-Contributors/AlgorithmsAndDataStructure#457]
## **`Fenwick Tree`** -

**I will add implementation of Fenwick Tree in C++ that supports two operations:** -
- Calculating the sum of elements in [l, r] for a one-dimensional array
- Increase value in arbitrary position in array by some amount

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by viagostini** [comment]
Can you please assign this one to me as well please?

**Comment by Manavi18** [comment]
I can implement it in python.

**Comment by ke-utkarsh** [comment]
Please allot me this, I can write correct, neat and detailed code in C++ as well as Python

**Comment by shubham5351** [comment]
@viagostini you can work on this issue.
