### ISSUE TITLE
Sieve of Atkin | Maths | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#46]
## **`Title`** - Sieve of Atkin in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Manoj13-coder** [comment]
May i contribute in it?

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @Manoj13-coder 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by Manoj13-coder** [comment]
May i send you PR on 1st of October please . so that this contribution will
also be counted for hacktober contest .

**Comment by SSKale1** [comment]
@Manoj13-coder Yes you can even now.

**Comment by codeperfectplus** [comment]
@Manoj13-coder We haven't received your PR yet. Are you still working on It?

**Comment by DeathcallXD** [comment]
Can I do this in C++ @codePerfectPlus

**Comment by Manoj13-coder** [comment]
i will send you pr in 5 minutes
