### ISSUE TITLE
Lowest Common Subsequence | Dynamic Programming | Python

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Contributors/AlgorithmsAndDataStructure#464]
## **`Title`** - Lowest Common Subsequence in Python

**what will change** -
I will be adding python code to solve the lowest common subsequence problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tarundhiraj** [comment]
I would like to work on this issue. Please assign this to me. Thanks.

**Comment by adityalata** [comment]
Would like to submit a Pull Request, can you please assign this issue to me.

**Comment by codeperfectplus** [comment]
The issue is already assigned in #111
