### ISSUE TITLE
Dutch National Flag | SortingAlgorithms | C++

### ISSUE THREAD

**Issue by agcy1210** [Py-Contributors/AlgorithmsAndDataStructure#465]
## **`3 way Quick Sort - Dutch National Flag Algorithm `** -

**what will change** -
In the folder AlgorithmsAndDataStructure/C++/Algorithms/SortingAlgorithms/ a new file called 3-way Quick Sort will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by agcy1210** [comment]
I would like to work on this issue. Please, assign it to me.

**Comment by shubham5351** [comment]
@agcy1210 you can work on this issue.

**Comment by agcy1210** [comment]
@shubham5351 The pull request has been made. Check it out and let me know if there are any changes needed.
