### ISSUE TITLE
Shortest Common Supersequence | Dynamic Programming | Python

### ISSUE THREAD

**Issue by tarundhiraj** [Py-Contributors/AlgorithmsAndDataStructure#466]
## **`Title`** - Shortest Common Supersequence in Python

**what will change** -
Adding new python code to implement shortest common supersequence
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tarundhiraj** [comment]
I would like to work on this issue. Please assign this issue to me. Thanks.

**Comment by ExpressHermes** [comment]
Assigned to @tarundhiraj
