### ISSUE TITLE
Red Black BSTs | Data Structure | Python

### ISSUE THREAD

**Issue by ugetshivam** [Py-Contributors/AlgorithmsAndDataStructure#469]
## **`Red Black Tree`** -

**Adding Red Black tree** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ugetshivam** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by ExpressHermes** [comment]
Assigned to @ugetshivam
