### ISSUE TITLE
Need Help in Creating new Issues

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#47]
If you are good in Data Structure and Algorithms, So you can create issues here. There are some rules.

- Before creating new issue check previous issues and Codes.
- Add proper `Title` and `Details`
- Title Format `Algorithms Name` | `Category` | `Language` 
Example - `Bubble Sort` | `SortingAlgorithms` | `Python`
- Create Different issue for C++ and Python.

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding,

**Comment by HimadriPathak** [comment]
can i work on this 
 insertion sort with python

**Comment by HimadriPathak** [comment]
Title :- insertion sort 

Type of Issue -
Adding New Code
Improving Documentation

Programming Language
Python

**Comment by HimadriPathak** [comment]
Title :- bubble sort 

Type of Issue -
Adding New Code
Improving Documentation

Programming Language
Python

**Comment by codeperfectplus** [comment]
@HimadriPathak Please create a new issue for each problem and make sure that issue doesn't exist before.

- Bubble sort algorithm already exists in code.
- Insertion sort is already assigned.

**Comment by HimadriPathak** [comment]
title: recursive function to reverse the string

language: python

**Comment by codeperfectplus** [comment]
Please create new issue not comment, check green button in the upper right corner for that @HimadriPathak

**Comment by AkshadK7** [comment]
Should I share some of my LeetCode Programs in a new Folder targeted at Competitive Programming Problems ?

**Comment by AkshadK7** [comment]
Sounds Good ???

**Comment by hacky1997** [comment]
@codePerfectPlus I have pulled an Ant colony optimization for the traveling salesman problem [issue](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/issues/124).

**Comment by HIMANSHU3107** [comment]
I'd love to work on this issue
