### ISSUE TITLE
Unbounded Knapsack Algorithm | Dynamic Programming | Python

### ISSUE THREAD

**Issue by tejasbirsingh** [Py-Contributors/AlgorithmsAndDataStructure#472]
## **`Title`** -  ****Unbounded Knapsack Problem in Python****

**what will change** 
- Clean Code implementation of Unbounded Knapsack Problem in Python

### Type of Issue 
- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by iamsriranga** [comment]
can i work on this

**Comment by tejasbirsingh** [comment]
I would like to work on this algorithm. I will write clean code along with explanation of every line

**Comment by ansh-lehri** [comment]
I would like to work on this issue.

**Comment by Alifbhanvadiya14** [comment]
I want to work on this issue

**Comment by shubham5351** [comment]
@tejasbirsingh you can work on this issue.

**Comment by absognety** [comment]
Is this PR still open?, isn't algorithm already added?

**Comment by codeperfectplus** [comment]
> Is this PR still open?, isn't algorithm already added?

It's still open.
