### ISSUE TITLE
Tree Data Structure  | Data Structures | C++

### ISSUE THREAD

**Issue by tejasbirsingh** [Py-Contributors/AlgorithmsAndDataStructure#475]
## **`Title`** - Implementation of Tree Data Structure in C++

**what will change** - Will add new code to implement Tree along with important functions

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tejasbirsingh** [comment]
I would like to work on this Tree implementation. I will implement it in c++ with clean code and description. Thanks

**Comment by mansijain014** [comment]
I would like to do this. Please assign it to me

**Comment by shubham5351** [comment]
@tejasbirsingh you can work on this issue.
