### ISSUE TITLE
8 puzzle Problem | Branch and Bound | C++

### ISSUE THREAD

**Issue by RitikaAg** [Py-Contributors/AlgorithmsAndDataStructure#477]
## **`Implementation of 8 puzzle problem using branch and bound`** -

**Will add code for 8 puzzle problem in C++ using branch and bound** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by RitikaAg** [comment]
Please assign this issue to me

**Comment by shubham5351** [comment]
@RitikaAg you can work on this issue.

**Comment by RitikaAg** [comment]
@shubham5351  Please review pull request #603
