### ISSUE TITLE
01 Knapsack | Algorithms | C++

### ISSUE THREAD

**Issue by ke-utkarsh** [Py-Contributors/AlgorithmsAndDataStructure#479]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gadde5300** [comment]
I would like to work on this.

**Comment by tejasbirsingh** [comment]
I would like to work on this! Thanks

**Comment by Anshul275** [comment]
Eager to work on this.

**Comment by ExpressHermes** [comment]
This issue already exists.
