### ISSUE TITLE
Different methods To handle categorical variables | Machine Learning | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#48]
I'd like to work on this issue of different methods to handle categorical variables.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @shubham5351

**Comment by nikhilgubbi** [comment]
I would like to take up this issue

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.

**Comment by codeperfectplus** [comment]
@shubham5351 Are you still working on this?

**Comment by shubham5351** [comment]
Yes, I'm working on it and soon I will complete it.
