### ISSUE TITLE
Gradient Descent| Machine Learning Algorithms | Python

### ISSUE THREAD

**Issue by saaranshM** [Py-Contributors/AlgorithmsAndDataStructure#480]
## **`Title`** - Adding Gradient Descent Algorithm in python

**what will change** - New code is added to GradientDescent.py

### Type of Issue - Adding new Code

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by MontyGhost** [comment]
I would like to work on this

**Comment by gadde5300** [comment]
Hey, I would like to work on this.

**Comment by saaranshM** [comment]
You all can check and make my code better.

**Comment by MontyGhost** [comment]
Sure, thanks!

**Comment by js899** [comment]
Can I work on this too ?

**Comment by saaranshM** [comment]
Yes

**Comment by codeperfectplus** [comment]
@saaranshM thanks for creating your issue, you can create PR from tomorrow. we received a lot of PR in the last 3-4 days. 
maybe by mistake, your PR was marked invalid. Please use flake8 for python code.

**Comment by premalrupnur** [comment]
Hey I too want to work on this issue!!
