### ISSUE TITLE
Disjoint Set Union | Graphs | C++

### ISSUE THREAD

**Issue by vinaypathak07** [Py-Contributors/AlgorithmsAndDataStructure#483]
## **`Title`** - Disjoint Set Union

**what will change** - Impletation of DSU and optimizing it to almost O(1) time complexity. It is used to find cycle in undirected graph.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by vinaypathak07** [comment]
I would like to work on it.

**Comment by shubham5351** [comment]
@vinaypathak07 you can work on this issue.

**Comment by Poojasingh5** [comment]
I want to work on this, kindly assign it to me.
