### ISSUE TITLE
Binary Search | Searching | Python

### ISSUE THREAD

**Issue by Hannibal404** [Py-Contributors/AlgorithmsAndDataStructure#487]
## **`Title`** - Binary Search

**what will change** - New code for Binary Search will be added

### Type of Issue - New Code

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i would like to work on this issue

**Comment by vaishnavi-1** [comment]
I would like to work on this.

**Comment by aryanjha22** [comment]
I want to work on this.

**Comment by mrinalTheCoder** [comment]
i would like to work on this

**Comment by evanessa234** [comment]
I would like to work on this issue
