### ISSUE TITLE
Longest Common Prefix | Algorithms | Python

### ISSUE THREAD

**Issue by rohangawhade** [Py-Contributors/AlgorithmsAndDataStructure#489]
## **`Title`** - Longest Common Prefix

**what will change** - New code will be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i would like to work

**Comment by rohangawhade** [comment]
Kindly assign me the issue that I made.

**Comment by codeperfectplus** [comment]
you can create PR from tomorrow. Please use flake8 standards for python codes.
