### ISSUE TITLE
Implementation of stack using list | Data Structures | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#49]
Can I work on this to build the stack using list.
Title :- Implementation of the stack using the list data structure in Python and perform the stack operations like push and pop.

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

**Comment by codeperfectplus** [comment]
- [x] @shubham5351 Assign Done

**Comment by shubham5351** [comment]
duplicate issue no - #13
