### ISSUE TITLE
Ternary Search | Algorithms| C++

### ISSUE THREAD

**Issue by flameslayer293** [Py-Contributors/AlgorithmsAndDataStructure#497]
## **`Ternary Search Algorithm`** -

**what will change** - Add ternary search algorithm

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Manavi18** [comment]
I can implement this in python.

**Comment by shubham5351** [comment]
@flameslayer293 you can work on this issue.
