### ISSUE TITLE
Tower of Hanoi | Data Structure | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#50]
Title ;- Tower of hanoi is a problem in which we have 3 rods and n disks.The objective of the problem is to move the entire stack to another rod, by following the below rules.
1) Only one disk can be moved at a time. 
2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack. 
3) No disk may be placed on top of a smaller disk

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codePerfectPlus** [comment]
- [x] Assign Done @shubham5351

**Comment by ayushijaiswal123** [comment]
I would like to work on this  issue. Please assign!

**Comment by shubham5351** [comment]
@ayushijaiswal123 you can work on this issue.

**Comment by shonali-ks** [comment]
can I work on it in C++ ? #167

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.
