### ISSUE TITLE
RodCutting | Algorithms | Python

### ISSUE THREAD

**Issue by KillMonger1** [Py-Contributors/AlgorithmsAndDataStructure#503]
### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by KillMonger1** [comment]
Hey, can this be assigned to me?

**Comment by Alifbhanvadiya14** [comment]
Hey, I want to work on this issue

**Comment by ExpressHermes** [comment]
Assigned to @KillMonger1
