### ISSUE TITLE
KMP Algorithm | Pattern Searching | C++

### ISSUE THREAD

**Issue by srivathsa729** [Py-Contributors/AlgorithmsAndDataStructure#506]
### Type of Issue - KMP Pattern Searching Algorithm in C++ is Missing 

- [x] Adding New Code for Algorithm

### Programming Language
- [x] C++

### Self Check 

- [x] Ask for issue assignment before making Pull Request.
- [x] Add your file in the proper folder
- [x] `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by srivathsa729** [comment]
@codePerfectPlus Please assign this issue to me, I would like to work on it

**Comment by srivathsa729** [comment]
assigned to @srivathsa729

**Comment by utushar25** [comment]
@codePerfectPlus please assign issue to me.
I will add kmp pattern searching algorithms

**Comment by deekshithanand** [comment]
I learnt this yesterday . I can code this either in python or cpp. Please assign it to me

**Comment by shubham5351** [comment]
@srivathsa729 you can work on this issue.
