### ISSUE TITLE
Readme doc for queues in c++/Data Structure/Queue is Missing

### ISSUE THREAD

**Issue by srivathsa729** [Py-Contributors/AlgorithmsAndDataStructure#511]
### Type of Issue - Readme doc for queues is missing

- [x] Improving Documentation

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by srivathsa729** [comment]
@ExpressHermes Please assign this issue to me.
I would like to work on this.
I will include definition of queue data structure, how the data structure can be used, operations on queues and it's applications.

**Comment by ExpressHermes** [comment]
Assigned to @srivathsa729

**Comment by Anmolreshi** [comment]
I would Like to work on this repo

**Comment by ExpressHermes** [comment]
Sure @Anmolreshi go ahead!

**Comment by Techkrish1** [comment]
Can you assign me to improve your README.md?
