### ISSUE TITLE
Jump Search | Searching Algorithms | C++

### ISSUE THREAD

**Issue by srivathsa729** [Py-Contributors/AlgorithmsAndDataStructure#516]
### Jump Search Algorithm in C++ is Missing

- [x] Add New Code for Jump Search Algorithm in C++

### Programming Language
- [x] C++

### Self Check 

- [x] Ask for issue assignment before making Pull Request.
- [x] Add your file in the proper folder
- [x] `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by srivathsa729** [comment]
@ExpressHermes Please assign this issue to me.
I would like to work on this.
I will implement Jump Search in C++.

**Comment by vatsalya-gupta** [comment]
I would like to work on this issue.

**Comment by SSKale1** [comment]
- [x]  Assigned to @srivathsa729 for issue opening.

**Comment by shubham5351** [comment]
Issue is already assigned please work on another issue.
