### ISSUE TITLE
Expression Tree Creation | Binary Trees | Python

### ISSUE THREAD

**Issue by adityalata** [Py-Contributors/AlgorithmsAndDataStructure#517]
## **`Expression Tree Creation in Python`** -

**what will change** - Addition of new script to create an Expression Tree in Python/DataStructure

### Type of Issue - Tree Algorithm

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by adityalata** [comment]
Would like to work on this, @codePerfectPlus @shubham5351 @reveurguy  please assign it to me, thanks!

**Comment by ExpressHermes** [comment]
Assigned to @adityalata
