### ISSUE TITLE
Expression Tree Evaluation | Binary Trees | Python

### ISSUE THREAD

**Issue by adityalata** [Py-Contributors/AlgorithmsAndDataStructure#518]
## **`Expression Tree Evaluation`** -

**what will change** -  Addition of new script to evaluate an Expression Tree in Python/DataStructure

### Type of Issue - ree Algorithm

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by adityalata** [comment]
Would like to work on this, @codePerfectPlus @shubham5351 @reveurguy please assign it to me, thanks!

**Comment by ExpressHermes** [comment]
Assigned to @adityalata

**Comment by tegamax** [comment]
@adityalata are you still working on this?

**Comment by adityalata** [comment]
Yeah @tegamax I have submitted a PR also!

**Comment by codeperfectplus** [comment]
@adityalata Then you have not mentioned this issue no. is your PR

**Comment by adityalata** [comment]
actually it got merged merged with the pending PR for #517
