### ISSUE TITLE
Left, Right, Top, Bottom View of Binary Tree | DSA | Python

### ISSUE THREAD

**Issue by adityalata** [Py-Contributors/AlgorithmsAndDataStructure#520]
## **`Left, Right, Top, Bottom View of Binary Tree`** -

**what will change** - addition of script for returning views of a given tree

### Type of Issue - New Task

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by adityalata** [comment]
Would like to work on this, @codePerfectPlus @shubham5351 @reveurguy please assign it to me, thanks!

**Comment by devangmukherjee** [comment]
I would like to work on this using C++ @codePerfectPlus  @shubham5351  @reveurguy

**Comment by ExpressHermes** [comment]
Assigned to @adityalata
