### ISSUE TITLE
Binary Insertion Sort | Sorting Algorithm | Python

### ISSUE THREAD

**Issue by PoojaSahore** [Py-Contributors/AlgorithmsAndDataStructure#524]
## **`Title`** - Binary Insertion Sort algorithm implementation in Python

**what will change** - Binary Insertion Sorting program will be added for Python

### Type of Issue -

Please add/delete options that are not relevant.

- Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

I would like to work on this.

**Comment by PoojaSahore** [comment]
Kindly assign this issue to me, @codePerfectPlus

**Comment by anirudhthakur** [comment]
can u assign it to me

**Comment by vatsalya-gupta** [comment]
I would like to work on this issue.

**Comment by ExpressHermes** [comment]
@PoojaSahore a PR for this issue has been merged so I am closing this issue. You can take any other issue.
