### ISSUE TITLE
Menu Driven Implementation | Singly Linked List | C++

### ISSUE THREAD

**Issue by NamanJain1902** [Py-Contributors/AlgorithmsAndDataStructure#526]
## **`Singly Linked List`** -

**Who Don't loves a easy menu driven program. All at one place.** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by falguni-k** [comment]
I can do it. Can you assign to me?

**Comment by kalrasagar** [comment]
Can you assign this to me I am well trained in C++.

**Comment by deekshithanand** [comment]
Hi there! I can to this in python or cpp. Please Assign it to me!!!!

**Comment by SSKale1** [comment]
- [x] Assigned to @nj1902 . You can create a PR now.
