### ISSUE TITLE
LCS and LIS | Dynamic Programming | C++ 

### ISSUE THREAD

**Issue by mukuakhilesh** [Py-Contributors/AlgorithmsAndDataStructure#53]
## **`Add Longest Common Subsequence and Longest Increasing Subsequence in C++`**

**what will change** - Addition of script for  LCS and LIS in Dynamic Programming in C++ and Python.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by mukuakhilesh** [comment]
@codePerfectPlus  I can take this up for C++.  Can you assign me.
Someone, else can take for Python.

**Comment by Sau28** [comment]
@codePerfectPlus, I can take this up for Python and C++ both. Should I create a separate issue or should I split it ?

**Comment by codeperfectplus** [comment]
@Sau28  create a separate issue for python, as C++ issue is assigned

**Comment by SSKale1** [comment]
@mukuakhilesh Make sure you make a separate issue for every problem or code you have to add. We'll be closing this rn and another PR for LCS has already been merged. So it is recommended that you make another issue to commit the LIS problem and we'll assign it to you.
