### ISSUE TITLE
Bubble Sort Algorithm | Algorithms | C++

### ISSUE THREAD

**Issue by Manjot-Singh-D** [Py-Contributors/AlgorithmsAndDataStructure#532]
## **`Title`** - Bubble sort modified

**what will change** - Adding a new feature to the Bubble sort algorithm which helped in improving the complexity of loop by using a bool value to restrict the loop when array is already sorted.  

### Type of Issue - Adding a new feature.

Please add/delete options that are not relevant.

- [] Adding New Code
- [x] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ExpressHermes** [comment]
This code has already been implemented in the initial commit.

**Comment by codeperfectplus** [comment]
duplicate issue
