### ISSUE TITLE
Vertical order Traversal of Binary Tree | DSA Binary Trees | C++

### ISSUE THREAD

**Issue by GunjanMA** [Py-Contributors/AlgorithmsAndDataStructure#533]
## Vertical order Traversal of Binary Tree 

**what will change** -

will add a cpp file containing code for vertical order traversal of a binary tree

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shubham5351** [comment]
@GunjanMA you can work on this issue.

**Comment by Shreejichandra** [comment]
Can I work on this issue?
Thank you.

**Comment by tegamax** [comment]
hi, can i work on this ?
