### ISSUE TITLE
Lowest Common Anscestor for a Tree in C++

### ISSUE THREAD

**Issue by vipenl26** [Py-Contributors/AlgorithmsAndDataStructure#536]
## what will change
create a trees folder in DS and add lca code to it.

## Problem

Given tree and n-1 edges.
Given two nodes a and b.
To find the lowest common ancestor of a and b in linear time.

input:
```
7
1 2
1 3
1 4
2 5
5 6
3 7
5
6
```
output:
```
2
```
can i work on this?

**Comment by codeperfectplus** [comment]
yes sure you are welcome.

**Comment by vipenl26** [comment]
> yes sure you are welcome.

ok thanks :)

**Comment by SSKale1** [comment]
PR Merged. Closing issue.
