### ISSUE TITLE
Interpolation Search | Searching Algorithms | C++

### ISSUE THREAD

**Issue by xma8lu** [Py-Contributors/AlgorithmsAndDataStructure#542]
##Interpolation Search -

Given a sorted array of n uniformly distributed values arr[], write a function to search for a particular element x in the array.

### Type of Issue -

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by xma8lu** [comment]
Please assign this issue to me

**Comment by codeperfectplus** [comment]
#358 Duplicate issue

**Comment by codeperfectplus** [comment]
Please don't create duplicate issues.
