### ISSUE TITLE
Interpolation Search | Searching Algorithms | Python

### ISSUE THREAD

**Issue by xma8lu** [Py-Contributors/AlgorithmsAndDataStructure#543]
## Interpolation Search -

Given a sorted array of n uniformly distributed values arr[], write a function to search for a particular element x in the array.
Thus, Interpolation search will be added in Python->Algorithms->Searching Algorithms .

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by xma8lu** [comment]
Please assign this to me

**Comment by ExpressHermes** [comment]
@aditya-gite-04 assigning to you
