### ISSUE TITLE
Subset-Sum Problems | Dynamic Programming | CPP

### ISSUE THREAD

**Issue by drj-sharma** [Py-Contributors/AlgorithmsAndDataStructure#544]
Subset Sum Problems

1. Classical Subset Sum Problem
2. Equal Sum Partition
3. Count Subsets of Given Sum

Adding New Problems to the Codebase.

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

Please Assign me this issue.

**Comment by gaurav101b** [comment]
Please assign this to me

**Comment by shubham5351** [comment]
duplicate issue no - #36
