### ISSUE TITLE
Tree implementation | Data Structure | Python

### ISSUE THREAD

**Issue by ExpressHermes** [Py-Contributors/AlgorithmsAndDataStructure#55]
## **Implement Tree in python** 

**what will change** - A new folder for Tree DS will be added in Python Data Structure

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ExpressHermes** [comment]
I will take this issue.

**Comment by HIMANSHU3107** [comment]
I'd love to work on this issue
