### ISSUE TITLE
Pollard's Rho Algorithm | Maths | Python

### ISSUE THREAD

**Issue by aaravm4** [Py-Contributors/AlgorithmsAndDataStructure#554]
## **`Add Pollard's Rho Algorithm,`** -

**what will change** - Python file with Pollard's Rho Algorithm implementation in `Python/Algorithms/Maths`.  

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by aaravm4** [comment]
Can I please be assigned this for hacktobefest?

**Comment by shubham5351** [comment]
@aaravm4 you can work on this issue.
