### ISSUE TITLE
Boruvka's Algorithm to find MST | Graph | C++

### ISSUE THREAD

**Issue by VyomGarg47** [Py-Contributors/AlgorithmsAndDataStructure#555]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language
Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by VyomGarg47** [comment]
Please assign this issue to me.

**Comment by shubham5351** [comment]
@VyomGarg47 you can work on this issue.
