### ISSUE TITLE
Divide and Conquer Algorithm to find maximum sum subarray | Algorithms | C++

### ISSUE THREAD

**Issue by VyomGarg47** [Py-Contributors/AlgorithmsAndDataStructure#556]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by VyomGarg47** [comment]
Please assign this issue to me.

**Comment by Tripathi-Alok** [comment]
Can you please assign this to me

**Comment by ExpressHermes** [comment]
@VyomGarg47 I think this has been implemented.

**Comment by shubham5351** [comment]
@VyomGarg47 you can work on this issue.

**Comment by abby3010** [comment]
I would like to work on this as I see there is no work done for a year on this issue.

@shubham5351 if possible please assign the issue to me!
