### ISSUE TITLE
Cycle Sort | SortingAlgorithms| Python

### ISSUE THREAD

**Issue by hot9cups** [Py-Contributors/AlgorithmsAndDataStructure#56]
# Title - Selection sort algorithm in Python

what will change -

Type of Issue -
Please add/delete options that are not relevant.

- [x] Adding New Code
Programming Language
Please add/delete options that are not relevant.

- [x] Python
Note - One Change in one Pull Request

🌟 Star it

🍴Fork it

🤝 Contribute to it!

Happy Coding

**Comment by hot9cups** [comment]
I will like to take this up, @codePerfectPlus

**Comment by hot9cups** [comment]
I'd like to take this up codePerfectPlus

**Comment by codeperfectplus** [comment]
ya sure, you are a maintainer. you can self assign task
