### ISSUE TITLE
Find the Intersection of two Arrays | DSA | C++

### ISSUE THREAD

**Issue by gaurav101b** [Py-Contributors/AlgorithmsAndDataStructure#562]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gaurav101b** [comment]
Please assign this issue to me

**Comment by deeksha207** [comment]
please assign to me this issue

**Comment by shubham5351** [comment]
@gaurav101b you can work on this issue.

**Comment by deeksha207** [comment]
I want to contribute in this issue , please assign this issue to me  :)

**Comment by shubham5351** [comment]
@gaurav101b can you please specify on which language would you like to work for this issue?

**Comment by shubham5351** [comment]
I'm closing this issue because you have selected two languages please select 1.
