### ISSUE TITLE
Union of two Arrays | Array | C++

### ISSUE THREAD

**Issue by gaurav101b** [Py-Contributors/AlgorithmsAndDataStructure#563]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gaurav101b** [comment]
Can I please be assigned this issue?

**Comment by Rishabrp99** [comment]
hey @gaurav101b This is Rishab here can you please assign it to me??? I would be very grateful for the same.

**Comment by gaurav101b** [comment]
> hey @gaurav101b This is Rishab here can you please assign it to me??? I would be very grateful for the same.

I don't have permission to assign man. Just create your own issue( make sure it's not already present) and ask for assignment there.

**Comment by rishav311** [comment]
I want to work on it

**Comment by ExpressHermes** [comment]
I think this is a very trivial algorithm. Please avoid working on such problems.
