### ISSUE TITLE
Circular queue | Data Structure | C++

### ISSUE THREAD

**Issue by kaushalkoladiya** [Py-Contributors/AlgorithmsAndDataStructure#571]
## **`Circular Queue`** 

**what will change** 

### Type of Issue -

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by kaushalkoladiya** [comment]
Can I proceed on this?

**Comment by garimamishraa** [comment]
Can I implement using python?

**Comment by ayushpattnaik** [comment]
Assign me this for c++

**Comment by harshitgupta2000** [comment]
I can do this in java or C please assign it to me.

**Comment by shubham5351** [comment]
@kaushalkoladiya you can work on this issue.

**Comment by kaushalkoladiya** [comment]
Submitted the PR.
