### ISSUE TITLE
Marathi number to English number | conversion  | Python

### ISSUE THREAD

**Issue by umangag07** [Py-Contributors/AlgorithmsAndDataStructure#576]
## Marathi number to English number

**what will change** - Add the full code.

### Type of Issue - new program

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by umangag07** [comment]
can i work on this?

**Comment by shubham5351** [comment]
@umangag07 you can work on this issue.

**Comment by umangag07** [comment]
can i add another code file in which i will read data from file ( which contains data with marathi number) and will write data to file
( which contains data with English numbers).

**Comment by shubham5351** [comment]
Yes, you can add it.

**Comment by umangag07** [comment]
With this issue no only?

**Comment by codeperfectplus** [comment]
create a new issue for that @umangag07
