### ISSUE TITLE
Strand Sort | Sorting Algorithm | Python

### ISSUE THREAD

**Issue by FergusYip** [Py-Contributors/AlgorithmsAndDataStructure#579]
## **Strand Sort** -

**what will change** - Add strand sort implementation in Python

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by FergusYip** [comment]
I would like to be assigned to this.

**Comment by shubham5351** [comment]
@FergusYip you can work on this issue.
