### ISSUE TITLE
Comb Sort| SortingAlgorithms | Python

### ISSUE THREAD

**Issue by hot9cups** [Py-Contributors/AlgorithmsAndDataStructure#58]
## **`Title`** - Comb Sort in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by HimadriPathak** [comment]
i would like to do this

**Comment by rexdivakar** [comment]
Issue assigned to @HimadriPathak 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding
