### ISSUE TITLE
Graph Algorithms | Graph | C++

### ISSUE THREAD

**Issue by chetanpandey1266** [Py-Contributors/AlgorithmsAndDataStructure#580]
## Graph Algorithms
**what will change** -
- Adjacency List implementation using list in C++
- Adjacency List implementation using unordered map in C++
- Breadth First Search
- Depth First Search

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by harshitgupta2000** [comment]
I want to add Hamiltonian cycle detection in graph please assign it to me. I will do it in C++

**Comment by chetanpandey1266** [comment]
Its not mentioned in the issue I generated. So its better that you generate a new issue for this

**Comment by chetanpandey1266** [comment]
Please assign it to me

**Comment by harshitgupta2000** [comment]
How? i would assign you

**Comment by SSKale1** [comment]
- [x] Assigned to @chetanpandey1266 .
Just make sure you add to the correct directory. C++/Data Structure/Trees/

**Comment by SSKale1** [comment]
And follow the contribution guidelines.

**Comment by chetanpandey1266** [comment]
@SSKale1 I think I should add to `C++/Data Structures/Graph/`

**Comment by SSKale1** [comment]
Ohh yes @chetanpandey1266 do it in Graph

**Comment by harshitgupta2000** [comment]
@SSKale1 I want to do it in python please assign it to me

**Comment by SSKale1** [comment]
@codePerfectPlus and @ExpressHermes Will be overlooking Python Issues.

**Comment by SSKale1** [comment]
@harshitgupta2000 Create a new issue if you want to do it in python.

**Comment by shriyaMadan** [comment]
Can I add Graph Traversals in C++?

**Comment by SSKale1** [comment]
@shriyaMadan BFS, DFS traversals have already been added. you can find some other algo that hasn't been added.
