### ISSUE TITLE
Topological Sort  | Algorithm | C++

### ISSUE THREAD

**Issue by tejasbirsingh** [Py-Contributors/AlgorithmsAndDataStructure#582]
## **`Title`** - Topological Sort in Graph

**what will change** - Add the C++ implementation of topological sort in graph

### Type of Issue - Algorithm Implementation in c++ addition

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] C++

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SSKale1** [comment]
This is a duplicate issue. #220
