### ISSUE TITLE
PigeonHole Sort| SortingAlgorithms | C++

### ISSUE THREAD

**Issue by hot9cups** [Py-Contributors/AlgorithmsAndDataStructure#59]
## **`Title`** - PigeonHole Sort in C++

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding.

**Comment by tusharsbauskar** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @tusharsbauskar

**Comment by hot9cups** [comment]
I'll take this up since no-one has volunteered.

**Comment by manningc33** [comment]
Can I be assigned this issue?
