### ISSUE TITLE
Heap | Data Structure | Python

### ISSUE THREAD

**Issue by chrismilson** [Py-Contributors/AlgorithmsAndDataStructure#590]
## **Heap**

The min heap is a data structure containing comparable values. If there are n values in the min heap it allows checking the minimum value in O(1) time, adding new elements in O(log n) time and removing the minimum element in O(log n) time.

We can implement a max heap by inverting the comparison between values, hence the lack of Min in the title.

**what will change?**

I will add an implementation of a min heap at `Python/DataStructure/Heap`. 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by chrismilson** [comment]
I would like to be assigned to this.

**Comment by harshitgupta2000** [comment]
Please assign it to me
