### ISSUE TITLE
Greedy Algorithm | Graphs|C++

### ISSUE THREAD

**Issue by harshitgupta2000** [Py-Contributors/AlgorithmsAndDataStructure#596]
C++ program for Prim's Minimum Spanning Tree

**what will change** -

Programming

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by harshitgupta2000** [comment]
@SSKale1  please assign it to me

**Comment by ExpressHermes** [comment]
@harshitgupta2000 greedy algorithm is a concept. It varies from question to question. How can you add it as a single algorithm?

**Comment by SSKale1** [comment]
What greedy Algorithm will you be implementing please be clear on it. And edit the issue and remove python from languages. 
And make sure an issue for a similar algorithm doesn't exist.

**Comment by ExpressHermes** [comment]
Please change it to something specific which has not been added/being worked upon in another issue.

**Comment by harshitgupta2000** [comment]
Now, if it is ok then assign me please

**Comment by SSKale1** [comment]
Duplicate Issue #86 . We'll be closing this issue now.
