### ISSUE TITLE
Heap Sort Algorithm implementation in Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#6]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Heap Sort Algorithm implementation in Python

**what will change** - @devil-cyber

**Assignees** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by devil-cyber** [comment]
can I work on this

**Comment by codeperfectplus** [comment]
- [x] @devil-cyber - Assigned

**Comment by devil-cyber** [comment]
I have one doubt when I should send the PR 1oct or before saying with respect to hacktoberfest

**Comment by codeperfectplus** [comment]
@devil-cyber , Make Your Pr between 1Oct- 31 Oct 2020

Happy coding

**Comment by devil-cyber** [comment]
thanks man

**Comment by sourabmaity** [comment]
i would like to solve this issue

**Comment by Suyash-Batham** [comment]
Could you please assign this issue to me? I would love to work on it.
