### ISSUE TITLE
count number 1 | Math | Python

### ISSUE THREAD

**Issue by sourabmaity** [Py-Contributors/AlgorithmsAndDataStructure#607]
## **`Title`** - Count 1
Take a user input to set highest bound and count how many 1 appear from 0 to that upper bound
Example - input : 13
              output : 6
explanation - 1,10,11,12,13
**what will change** -
put your code inside "Maths" folder
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to work in this issue

**Comment by bhati-mukesh** [comment]
Hello, can you please assign this issue to me?

**Comment by sourabmaity** [comment]
please label it as a hacktoberfest-accepted
