### ISSUE TITLE
BogoSort| Algorithms-SortingAlgorithms| Python

### ISSUE THREAD

**Issue by ristovao** [Py-Contributors/AlgorithmsAndDataStructure#617]
## **`BogoSort in python`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ristovao** [comment]
Please assign this to me.

**Comment by Hridoy-31** [comment]
Is this issue assigned to someone ??

**Comment by aa-ryan** [comment]
I would love to contribute to it.
Please assign it to me!

**Comment by PrathamesR** [comment]
Seems simple would love this as my first contribution
