### ISSUE TITLE
Add Depth First Search and Breadth First Search for Tree DS | Algorithm | Python

### ISSUE THREAD

**Issue by ExpressHermes** [Py-Contributors/AlgorithmsAndDataStructure#62]
## **Add Depth-First Search and Breadth-First Search for Tree DS** -

**what will change** - A new file added to Tree DS Folder

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ExpressHermes** [comment]
For readability and decreasing complexity, It will be better to keep these algos in Tree DS folder. I will work on this issue

**Comment by sravanireddy1102** [comment]
Can I work on this?

**Comment by ExpressHermes** [comment]
@sravanireddy, I am already working it. You can work on any other issue which is not assigned. If you have any suggestion for a new algorithm, you can open a new issue.
