### ISSUE TITLE
Maximum Pairwise Product | Algorithms | C++

### ISSUE THREAD

**Issue by shrey27tri01** [Py-Contributors/AlgorithmsAndDataStructure#623]
## **`Maximum Pairwise Product`** -

**What will change** -
Add code for the Maximum Pairwise Product problem, in C++.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by shrey27tri01** [comment]
Can I be assigned this issue?

**Comment by Rohit-varma** [comment]
Can you assign the issue to me?
I am willing to contribute

**Comment by ritikajain0** [comment]
Can i contribute to this issue ?

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rahulmishra11** [comment]
Please assign this task to me.

**Comment by kokilgupta** [comment]
Can I contribute to this issue?

**Comment by SSKale1** [comment]
- [x] Assigned to @shrey27tri01 for Issue Creation

**Comment by shrey27tri01** [comment]
@codePerfectPlus @SSKale1  I have raised a PR [here](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/pull/653). Can you please review it?
