### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by KaushalDevrari** [Py-Contributors/AlgorithmsAndDataStructure#637]
Can you please label it with hacktoberfest.

_Originally posted by @KaushalDevrari in https://github.com/Py-Contributors/AlgorithmsAndDataStructure/pull/612#issuecomment-704684014_

**Comment by codeperfectplus** [comment]
We don't support Spam. we believe in the spirit of Hacktober to support the open-source community. Please follow the guidelines for valid Hacktober label, Spamming may lead you to ban from hacktober.
