### ISSUE TITLE
Dijkstra's Shortest Path Algorithm | Shortest Path Algorithms | Python

### ISSUE THREAD

**Issue by aicarras** [Py-Contributors/AlgorithmsAndDataStructure#64]
## Dijkstra's Shortest Path Algorithm | Shortest Path Algorithm | Python

**what will change** - new directory named Shortest Path Algorithms. Within that new file Dijkstras.py containing an implementation of Dijkstra's shortest path algorithm

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by aicarras** [comment]
Can I make the pull request?

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @AlexisJCarras 

Make your PR between 1 Oct - 31 Oct for valid Hacktober PR

**Comment by codeperfectplus** [comment]
@sravanireddy1102 issue is already assigned, wait for new issues
