### ISSUE TITLE
Topological Sort  | Sorting | Python

### ISSUE THREAD

**Issue by Kamesh-Mishra** [Py-Contributors/AlgorithmsAndDataStructure#649]
## **`Title`** - Topological Sort | Sorting Algorithm | Python

**what will change** - Adding new program for Topological Sort | Sorting Algorithm in Python

### Type of Issue -

- [x]  Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Kamesh-Mishra** [comment]
I would like to contribute, can you please assign me.

**Comment by rapunzel127** [comment]
@Kamesh-Mishra Can I please work on it?

**Comment by Kamesh-Mishra** [comment]
@ExpressHermes  I completed,, check my PR.

**Comment by Kamesh-Mishra** [comment]
@rapunzel127 sorry I did it. there are a lot you will find better one

**Comment by ExpressHermes** [comment]
PR merged

**Comment by Kamesh-Mishra** [comment]
@ExpressHermes ok
