### ISSUE TITLE
Radix Sort | Sorting Algorithms | Python

### ISSUE THREAD

**Issue by AngryKiddo** [Py-Contributors/AlgorithmsAndDataStructure#65]
## **`Title`** - Radix Sort using Python

**what will change** -

### Type of Issue - Sorting Algorithms

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ItsOKayCZ** [comment]
Hello, can I work on this issue?

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @ItsOKayCZ
