### ISSUE TITLE
Binary Search Tree | Data Structure| Python

### ISSUE THREAD

**Issue by Harshalszz** [Py-Contributors/AlgorithmsAndDataStructure#659]
## **`Binary Search Tree`** -

**I will add file  BST.py** -

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] Python

**Comment by Harshalszz** [comment]
I would like to be assigned to this issue, Thank you!

**Comment by Shreejichandra** [comment]
I also want to work on this issue.
Thank you.

**Comment by ExpressHermes** [comment]
An issue already exists for this.
