### ISSUE TITLE
Quick Sort | SortingAlgorithms | C++

### ISSUE THREAD

**Issue by Sau28** [Py-Contributors/AlgorithmsAndDataStructure#66]
## **`Title`** - Quick Sort in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AngryKiddo** [comment]
I would like to work on this

**Comment by codeperfectplus** [comment]
@Sau28 @AngryKiddo
 The duplicate issue, Please check the code and issue. Issue already created

**Comment by Sau28** [comment]
@codePerfectPlus, can you verify, i do not see any open/closed issue on the same.
Thanking you in advance.

**Comment by codeperfectplus** [comment]
check issue no. #4
