### ISSUE TITLE
Wiggle Sort | Sorting | Python

### ISSUE THREAD

**Issue by Kamesh-Mishra** [Py-Contributors/AlgorithmsAndDataStructure#662]
## **`Title`** - Wiggle Sort | Sorting Algorithm | Python

**what will change** - Implementation of wiggle sort algorithm

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- 

- [x]  Ask for issue assignment before making Pull Request.
- [x] Add your file in the proper folder
- [x]  `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Kamesh-Mishra** [comment]
I would Like to Work on this issue, can you please assign me

**Comment by rapunzel127** [comment]
Can I please work on it?
