### ISSUE TITLE
Quick Sort | Sorting Algorithms | Python

### ISSUE THREAD

**Issue by Sau28** [Py-Contributors/AlgorithmsAndDataStructure#67]
## **`Title`** - Quick Sort in Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AngryKiddo** [comment]
I want to work on this!!

**Comment by codeperfectplus** [comment]
@Sau28 @AngryKiddo
The duplicate issue, Please check the code and issue. Issue already created

**Comment by Sau28** [comment]
@codePerfectPlus, can you verify again ?
I do not see any open/closed issue on this.

**Comment by codeperfectplus** [comment]
@Sau28  you want to work on this issue.

code is incomplete. My fault

**Comment by Sau28** [comment]
Yes

**Comment by codeperfectplus** [comment]
- [x] @Sau28 assigned

**Comment by anoop447** [comment]
Can i work on this pls.

**Comment by SupraJ1** [comment]
Can I work on this

**Comment by miczza** [comment]
I would like to be assigned to this. Thank you.

**Comment by DilshanDeAlmeida** [comment]
Assign this issue to me. I know how to implement it. Python #67
