### ISSUE TITLE
Documentation | Math | Python

### ISSUE THREAD

**Issue by ghost** [Py-Contributors/AlgorithmsAndDataStructure#683]
## **`Title`** - PEP8 Standard and Line Comments

**what will change** -

Following files : 

AlgorithmsAndDataStructure/Python/Algorithms/Maths/PollardRho.py
AlgorithmsAndDataStructure/Python/Algorithms/Maths/countDigitOne.py 
AlgorithmsAndDataStructure/Python/Algorithms/Maths/decimalToN_base.py 
AlgorithmsAndDataStructure/Python/Algorithms/Maths/sumofdigits.py

### Type of Issue -

More structured code with proper line comments required.

- [x] Improving Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ghost** [comment]
Kindly assign me this issue. @codePerfectPlus

**Comment by Pitambara16** [comment]
Hey, @JenishRudani I would like to help with the documentation here.

**Comment by Techkrish1** [comment]
can you assign me one? I can implement this.
