### ISSUE TITLE
Graph Algorithms | Data Structures | Python 

### ISSUE THREAD

**Issue by chetanpandey1266** [Py-Contributors/AlgorithmsAndDataStructure#684]
## **`Graph Algorithms`** -

**what will change** -

Add a class implementing following
- unidirected graph
- breadth first search
- depth first search

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by chetanpandey1266** [comment]
Please assign me to this issue

**Comment by chetanpandey1266** [comment]
Please assign me to this issue

**Comment by tenzu15** [comment]
I would like to do this, could you assign it to me?

**Comment by amitrajitbose** [comment]
Interested to contribute, please assign if necessary. @chetanpandey1266 @codePerfectPlus

**Comment by Techkrish1** [comment]
I am interested to contribute on this issue. can you assign me to implement the code?
