### ISSUE TITLE
Max Sum Without Adjacent Elements | Dynamic Programming | C++

### ISSUE THREAD

**Issue by mallesham108** [Py-Contributors/AlgorithmsAndDataStructure#685]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by mallesham108** [comment]
Given a 2 x N grid of integer, A, choose numbers such that the sum of the numbers
is maximum and no two chosen numbers are adjacent horizontally, vertically or diagonally, and return it.

The above mentioned is the question.

Please,Assign it to me

**Comment by DhawalKhapre** [comment]
please assign this issue to me @malleshamshivs

**Comment by mallesham108** [comment]
@DhawalKhapre I am not the admin of this repository. I can't assign this issue to anyone. Whenever you want to solve a problem, Try to create a new issue by yourself and ask the admins to assign it to you. These issues which are made by the people are asking the admins to assign it to them. So, please create issue on your own, by using "New issue" on the top right.. and create issue and get it assigned to you by admins ,then make the pull request after getting assigned
