### ISSUE TITLE
RNN | Neural Network | Python

### ISSUE THREAD

**Issue by pikachu28** [Py-Contributors/AlgorithmsAndDataStructure#687]
## **Implementing Recurrent Neural Network From [Scratch**] -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by pikachu28** [comment]
Please assign this issue to me : ) @ExpressHermes

**Comment by ExpressHermes** [comment]
@pikachu28 assigned to you. Happy Hacktoberfest 🚀
