### ISSUE TITLE
Bucket Sort | Sorting Algorithms | C++

### ISSUE THREAD

**Issue by Sau28** [Py-Contributors/AlgorithmsAndDataStructure#69]
## **`Title`** - Bucket Sort in C++

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AngryKiddo** [comment]
I want to work on this.

**Comment by codeperfectplus** [comment]
- [x] @Sau28  please comment too if you want to take issue. I assigned 2 issues to @AngryKiddo

**Comment by Sau28** [comment]
Hey, I will like to take this issue up.

**Comment by codeperfectplus** [comment]
- [x] Issue assigning to @Sau28
