### ISSUE TITLE
Implement Queue in C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#7]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Implement Queue in C++

**what will change** -

**Assignees** - @d2Anubis 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by d2Anubis** [comment]
I would like to work on this.

**Comment by ayushijaiswal123** [comment]
I will like to work on this issue. Please assign!

**Comment by codeperfectplus** [comment]
@ayushijaiswal123 This task is already assigned to @d2Anubis, Please check new issues.

New issues coming soon, Keep an eye out

**Comment by d2Anubis** [comment]
Done and created a pull request :) This issue needs to be closed now.

**Comment by SSKale1** [comment]
PR Merged. Closing issue.
