### ISSUE TITLE
Implementation of Stack using C++ | Data Structures | C++

### ISSUE THREAD

**Issue by AngryKiddo** [Py-Contributors/AlgorithmsAndDataStructure#70]
## **`Title`** - Implementation of stack using C++

**what will change** -

### Type of Issue - Data Structures

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AngryKiddo** [comment]
I would like to work on this.

**Comment by codeperfectplus** [comment]
- [x] Issue assigned to @AngryKiddo

**Comment by trivediavinash** [comment]
@codePerfectPlus  can i also work on this issue

**Comment by chinmaygupta14** [comment]
@codePerfectPlus can I work on this issue.

**Comment by SSKale1** [comment]
Multiple implementations of Stack have been merged. We'll be closing this issue for now.
