### ISSUE TITLE
Gravity Sort | Sorting Algorithm | Python

### ISSUE THREAD

**Issue by soum-sr** [Py-Contributors/AlgorithmsAndDataStructure#702]
## Gravity Sort/Bead Sort algorithm

I will add a new file ```GravitySort.py``` at ```Python/Algorithms/SortingAlgorithms```

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by soum-sr** [comment]
I would like to be assigned to this issue. Thank you

**Comment by Jeewantha-Madubashana** [comment]
Hi, I would like to work on this feature. Please assign it to me.

**Comment by mahesh-kumaran** [comment]
Hi, Can you please assign it to me ? This would be a great start for me. ! Thanks !

**Comment by Shreyagundu** [comment]
I would like to take up this issue.
