### ISSUE TITLE
Dice Throw | Dynamic Programming | Python

### ISSUE THREAD

**Issue by suman2826** [Py-Contributors/AlgorithmsAndDataStructure#703]
## Dice Throw

I will add a new file to AlgorithmsAndDataStructure/Python/Algorithms/Dynamic Programming

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by suman2826** [comment]
I would like to be assigned to this , Thank you!

**Comment by ExpressHermes** [comment]
@suman2826 can you elaborate a little about what this algo will do.

**Comment by suman2826** [comment]
Here we will be given n dices with f number of faces for each dice and a integer X. We have to find the number of ways to get sum X which will be equal to the summation of values on each face when all the dice are thrown.

For this problem I am going to use Dynamic Programming because it exhibits overlapping Subproblem.

**Comment by ExpressHermes** [comment]
@suman2826 assigning to you
