### ISSUE TITLE
Neural Networks | Deep Learning | Python

### ISSUE THREAD

**Issue by reach-the-sky** [Py-Contributors/AlgorithmsAndDataStructure#704]
## **`Neural Networks from scratch`** -

**I'll add a python neural networks file from scratch** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by reach-the-sky** [comment]
Please assign this to me.

**Comment by errpv78** [comment]
Do you require simple neural network, like an example, or any special architecture implementation on a dataset?
