### ISSUE TITLE
Number of palindromic Paths in a matrix | Recursion Algorithms | Python

### ISSUE THREAD

**Issue by suman2826** [Py-Contributors/AlgorithmsAndDataStructure#708]
## Number of palindromic paths in a matrix

I will add a new file to AlgorithmsAndDataStructure/Python/Algorithms/Recursion Algorithms

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by suman2826** [comment]
I would like to be assigned to this issue, Thank you!

**Comment by shubham5351** [comment]
@suman2826 you can work on this issue.
