### ISSUE TITLE
Jump Search | Searching Algorithm| Python

### ISSUE THREAD

**Issue by Viper2211** [Py-Contributors/AlgorithmsAndDataStructure#710]
## **`Jump Search`**

I will add a new file to AlgorithmsAndDataStructure/Python/Algorithms/SearchingAlgorithms

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by sourabmaity** [comment]
I want to work in this issue

**Comment by AniruthA** [comment]
This was done in a pull request already. Sorry about that.

**Comment by Viper2211** [comment]
Could you assign this to me as well

**Comment by shubham5351** [comment]
Duplicate issue no- #10
