### ISSUE TITLE
KMP Algorithm | Pattern Searching | Python

### ISSUE THREAD

**Issue by DhawalKhapre** [Py-Contributors/AlgorithmsAndDataStructure#712]
## **`KMP Algorithm`** 

**what will change** - Implementation of KMP Algorithm for Pattern Searching

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by DhawalKhapre** [comment]
I would like to contribute to this issue, can you please assign this to me?

**Comment by shubham5351** [comment]
Duplicate issue no - #40
