### ISSUE TITLE
Knapsack Problem solution in C++ | Dynamic Programming | C++

### ISSUE THREAD

**Issue by AngryKiddo** [Py-Contributors/AlgorithmsAndDataStructure#72]
## **`Title`** - Knapsack Problem solution in C++

**what will change** -

### Type of Issue - Dynamic Programming

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Sau28** [comment]
I want to work on this issue, can you assign it to me?
Thanks.

**Comment by arnabsen1729** [comment]
I am up for this. @AngryKiddo please assign me.

**Comment by codeperfectplus** [comment]
- [x] @arnabsen1729 issue assigned

**Comment by Rj-coder-iitian** [comment]
I can do this in C language., please assign me if you want a solution in C language.

**Comment by arnabsen1729** [comment]
@Rj-coder-iitian create a new issue, I will be submitting a PR on this issue.

**Comment by SSKale1** [comment]
PR Merged Closing issue.
