### ISSUE TITLE
Subset sum count | Dynamic Programming | C++

### ISSUE THREAD

**Issue by yashgupta18** [Py-Contributors/AlgorithmsAndDataStructure#720]
## **`Subset sum count`** 

**what will change** - Add a Subset sum count C++ program in AlgorithmsAndDataStructure/C++/Algorithms/DynamicPrograming/

### Type of Issue - Adding new code
- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by yashgupta18** [comment]
I would like to take up this issue. Thanks.

**Comment by Shreyagundu** [comment]
I would like to take up this issue.

**Comment by MukundPNayak** [comment]
> ## **`Subset sum count`**
> **what will change** - Add a Subset sum count C++ program in AlgorithmsAndDataStructure/C++/Algorithms/DynamicPrograming/
> 
> ### Type of Issue - Adding new code
> * [x]  Adding New Code
> 
> ### Programming Language
> * [x]  C++

I would like to work on this issue

**Comment by daviddevore** [comment]
Can I be assigned to this?

**Comment by daviddevore** [comment]
> ## **`Subset sum count`**
> **what will change** - Add a Subset sum count C++ program in AlgorithmsAndDataStructure/C++/Algorithms/DynamicPrograming/
> 
> ### Type of Issue - Adding new code
> * [x]  Adding New Code
> 
> ### Programming Language
> * [x]  C++

Can I be assigned to this?

**Comment by daviddevore** [comment]
@codePerfectPlus thank you for assigning it to me! What do I need to do to get it reviewed?

**Comment by codeperfectplus** [comment]
Hi, @daviddevore PLease make a PR. anyone from our will review the code. 

PLease check [Contributing guidelines](https://github.com/codePerfectPlus/AlgorithmsAndDataStructure/blob/master/CONTRIBUTING.md) for details guidelines for making a PR. 

Thanks for your contrinution in advance.

Happy Coding,
