### ISSUE TITLE
Detect a Loop in a Linked List | Data Structure | C/C++

### ISSUE THREAD

**Issue by falguni-k** [Py-Contributors/AlgorithmsAndDataStructure#722]
## **`Detect a Loop in a Linked List`** -

Add a file that contains the code of detecting a loop in a linked list.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by falguni-k** [comment]
I would like to work on this in c++

**Comment by ITES7321** [comment]
Can I work on this?

**Comment by ashvinimore** [comment]
Hello falguni,
Can I work on this task in python?
Thank You

**Comment by falguni-k** [comment]
Hii @ashvinimore I cannot assign it. I'm waiting to be assigned myself so that I can work in C++.

**Comment by shubham5351** [comment]
@falguni-k you can work on this issue and also remove the python checkmark.

**Comment by shubham5351** [comment]
If anyone want to work on this issue using python then please create the new issue I will assign it to you but on FCFS basis.

**Comment by sneha281** [comment]
I can do this code please assign me dear @falguni-k

**Comment by sneha281** [comment]
@shubham5351  I want to work on this issue using python

**Comment by sneha281** [comment]
I can do this task in c , c++ , or in Python @falguni-k

**Comment by falguni-k** [comment]
Hello @sneha281 as @shubham5351 has mentioned, if you want to do this in python, create a new issue. He can assign you. I can't assign.
