### ISSUE TITLE
Jump Search | Searching Algorithm | Python

### ISSUE THREAD

**Issue by mohammedshibinv** [Py-Contributors/AlgorithmsAndDataStructure#724]
## **`Title`** -Jump Search

**what will change** - Implementation of Jump Searching using python

### Type of Issue 

- [x] -Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by mohammedshibinv** [comment]
I would like to take up this issue.
Could you please assign me

**Comment by Stealth-py** [comment]
Can I take up this issue?
Can you assign this to me?

**Comment by shubham5351** [comment]
Duplicate issue no - #10

**Comment by codeperfectplus** [comment]
There is no response from the previous issue so assigning again to new person.

**Comment by MohdShibin** [comment]
so can you please assign this to me?

**Comment by codeperfectplus** [comment]
it's assigned to you @MohdShibin

**Comment by purva-saxena** [comment]
i would like to request you to assign this  to me!!
can u assign this to me??
i will be thankful!
