### ISSUE TITLE
Fibonacci Search | Searching Algorithms | C++

### ISSUE THREAD

**Issue by Sau28** [Py-Contributors/AlgorithmsAndDataStructure#73]
## **`Title`** - Fibonacci Search in C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Sau28** [comment]
I will like to work on this issue.

**Comment by Priyanshu-official** [comment]
@Sau28 I will like to work on this issue.

**Comment by codeperfectplus** [comment]
- [x] Issue assigned, @Sau28 

You have assigned to a lot of issues, Please give a chance to others for HacktoberFest.

**Comment by sourabmaity** [comment]
i would like to solve

**Comment by Priyanshu-official** [comment]
@SOURAB-BAPPA  it's closed i think

**Comment by SSKale1** [comment]
@Priyanshu-official This issue is still open, but is assigned to @Sau28
