### ISSUE TITLE
Maximum Product subarray | Dynamic Programming | Python

### ISSUE THREAD

**Issue by 2knal** [Py-Contributors/AlgorithmsAndDataStructure#733]
## Maximum Product subarray | Dynamic Programming | Python

Added Maximum Product subarray to the Dynamic Programming section in Python language.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by 2knal** [comment]
I would like to be assigned to this issue. <br>
Thank you!

**Comment by btapash** [comment]
I already worked on writing many algorithms. Can you assign it to me?
