### ISSUE TITLE
Roman To Integer | Math | Python

### ISSUE THREAD

**Issue by X0rD3v1L** [Py-Contributors/AlgorithmsAndDataStructure#734]
## **`Roman to Integer`** -

**Will  implement the conversion program** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by RimorRes** [comment]
Hi!
I'd like to take a gander at this issue!
Could I please get assigned to it?

**Comment by priyadarshan1995** [comment]
Hey, Could you pls assign this issue to me? I can start on it immediately.

**Comment by btapash** [comment]
Hey! I already worked on writing many algorithms. Can you assign it to me?
