### ISSUE TITLE
Algorithm name | Category | Language

### ISSUE THREAD

**Issue by devdev606** [Py-Contributors/AlgorithmsAndDataStructure#738]
## **`Hacktoberfest`** -

**what will change** -

### Type of Issue - new beginners

Please add/delete options that are not relevant.

- [v] Adding New Code
- [v] Improving Code
- [v] Improving Documentation
- [v] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [v] Python
- [v] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Godspower-Eze** [comment]
Please explain better

**Comment by codePerfectPlus** [comment]
Incomplete information of issue.
