### ISSUE TITLE
vectors | data structure | c++

### ISSUE THREAD

**Issue by Saurabh-Dadhich** [Py-Contributors/AlgorithmsAndDataStructure#740]
## **`Title`** - vectors in c++

**what will change** - Data type-vectors will be added in c++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Saurabh-Dadhich** [comment]
please assign me for this task

**Comment by s-bose** [comment]
Hi! I am interested in this. Can you tell me in a bit detail about what exactly do you need?

**Comment by Saurabh-Dadhich** [comment]
hey, I have send you pull request #745, please review it

**Comment by Saurabh-Dadhich** [comment]
hi @codePerfectPlus  please review my pull request #745

**Comment by victoriamoya** [comment]
Can I be assigned this?

**Comment by Jinfan-Tu** [comment]
Can u assign me this task?
