### ISSUE TITLE
LRU Cache | Data Structure | Python

### ISSUE THREAD

**Issue by amitrajitbose** [Py-Contributors/AlgorithmsAndDataStructure#746]
## **`Title`** -

Add well-tested implementation for LRU cache.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by owlhoo** [comment]
### Title - LRU Cache implementation

**Type of Issue - Operating System Cache Algorithm**

- [x]  Adding New Code

**Programming Language**

- [x]  Python

**Self Check**

 - [x] Ask for issue assignment before making Pull Request.
 - [x] Add your file in the proper folder
 - [x] Clean Code and Documentation for better readability
 - [x] Add Title and Description of the program in the file

Discord server email - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by aneshujevic** [comment]
Could you assign it to me, please? :)

**Comment by amitrajitbose** [comment]
This issue has been resolved in PR #747 
@codePerfectPlus 
Kindly review
