### ISSUE TITLE
Addition of numbers without using arithmetic operator | Data Structures | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#75]
## **`Title`** - Addition of numbers without using arithmetic operator

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Priyanshu-official** [comment]
@shubham5351 I will like to work on this issue.

**Comment by Pinak-coder** [comment]
I would like to contribute to the code.

**Comment by Pinak-coder** [comment]
I would like to upload the code for binary search.

**Comment by Pinak-coder** [comment]
@shubham5351, I would like to upload the code for binary search.

**Comment by Priyanshu-official** [comment]
@Pinak-coder comment Where Issue is Mentioned So you can Assigned

**Comment by Pinak-coder** [comment]
@Priyanshu-official  I didnt get U...I would like to work on this code..

**Comment by Priyanshu-official** [comment]
@shubham5351 Hii Shubham Pls close this
