### ISSUE TITLE
Factorial | Algorithms | C++

### ISSUE THREAD

**Issue by sparkskapil** [Py-Contributors/AlgorithmsAndDataStructure#754]
## ```Title```- Factorial | Recursion
I would like to add new code in the Algorithms folder for Recursion under C++

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check
- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- Clean Code and Documentation for better readability
- Add Title and Description of the program in the file

🌟 Star it 🍴Fork it 🤝 Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tiara1** [comment]
I'd like to take this up.

**Comment by sparkskapil** [comment]
> I'd like to take this up.

A PR is already raised for this issue.
