### ISSUE TITLE
Perform various operations on sparse matrix | Data Structure | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#76]
## **`Title`** - Perform various operations like addition, subtraction and so on, on the sparse matrix.

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AngryKiddo** [comment]
I would like to work on this

**Comment by codeperfectplus** [comment]
@AngryKiddo You have assigned to a lot of issues already. Please give a chance to new contributors too. I hope you will understand.

Thanks,
Happy Coding

**Comment by vatsalya-gupta** [comment]
I would like to work on this.

**Comment by shubham5351** [comment]
@vatsalya-gupta you can work on this issue I have assigned it to you.

**Comment by vatsalya-gupta** [comment]
Sorry, due to unforeseeable circumstances, I will not be able to continue on this issue. Hope you understand. Thank You. @shubham5351

**Comment by rrrrrrmb** [comment]
hey if this issue is still up I can work on it!

**Comment by codeperfectplus** [comment]
- [x] @mdb571 assigning the issue
