### ISSUE TITLE
LinkedList | Datastructures | C++

### ISSUE THREAD

**Issue by sparkskapil** [Py-Contributors/AlgorithmsAndDataStructure#760]
## **`Implement remove and insertAt method for linked list class.`**

**what will change** -
The C++/Data Structure/Linked List/linkedList.cpp will be changed. 
Two new methods will be added.
1. remove: It will take the index of the node and remove it from the list. 
2. insertAt: It will take the index and data and create a node and insert at the specified index of the list. 

### Type of Issue -

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language:

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sparkskapil** [comment]
I'll take this issue.

**Comment by purva-saxena** [comment]
i would like to request you to assign me this program!! i will be thankful !

**Comment by SauravBaba** [comment]
@sparkskapil please assign to me ,I done it in advanced ,I also done pull request, thankyou!!
