### ISSUE TITLE
Algorithm name | Category | Language

### ISSUE THREAD

**Issue by Garg17a** [Py-Contributors/AlgorithmsAndDataStructure#77]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
incomplete information for the issue, @Garg17a 

Closing now
