### ISSUE TITLE
Ternary Search | Searching Algorithm | C++/Python

### ISSUE THREAD

**Issue by atarax665** [Py-Contributors/AlgorithmsAndDataStructure#773]
## **`Title`** - Ternary Search

**what will change** - Implement Ternary Search Algorithm in C++ and Python

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ameyanrd** [comment]
Hi, I would like to take up this issue.

**Comment by twentyonedot** [comment]
@atarax665  Can you assign this to me. I want to work on this issue.

**Comment by Ankin01** [comment]
@atarax665 I would like to work on this issue

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
@atarax665  Please assign this issue to me , I am new to open-source and looking forward for opportunities to contribute

**Comment by adarsh1mehra** [comment]
hi @atarax665, I request you to kindly assign this issue to me.  I've been working on various searching and sorting issues for quite a long and I feel comfortable to work on this issue.

**Comment by farFromShallow101** [comment]
Hello. I am totally new to open source. However, I am well acquainted with the sorting and searching algorithms in C++ language. I would be really grateful if you assign this issue to me

**Comment by manralhemant10** [comment]
hi, can you assign this issue to me

**Comment by Jehjay** [comment]
Hi there, would like some help to solve this issue an add from you will do just that.

**Comment by lakshya8066** [comment]
Hi!
Can you assign it to me?

**Comment by pratyush-patwa** [comment]
Hello @atarax665 Could you assogn this to me?

**Comment by DilshanDeAlmeida** [comment]
Hi there @atarax665 can you assign me to this?
I have implemented the solution in python. !!

**Comment by DilshanDeAlmeida** [comment]
Hi @atarax665 can you assign me to this. I have the working implemented in python.

**Comment by tanishq-1011** [comment]
Hello @atarax665 Could you assign this to me?

**Comment by hidekiriyuga** [comment]
assign me!
