### ISSUE TITLE
Evaluation of Prefix and Postfix Expression | Data Structures | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#78]
## **`Title`** - Evaluation of Prefix and Postfix Expressions

Evaluation of Postfix Expression : 

Input : 432*+5-
Output : 5

Evaluation of Prefix Expression : 

Input : -*+4325
Output : 9

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by feyre-2001** [comment]
Hi! Would love to take up this issue!

**Comment by shubham5351** [comment]
@feyre-2001 you can work on  this issue.

**Comment by sravanireddy1102** [comment]
Hey!!I would like to take up this issue

**Comment by codeperfectplus** [comment]
@sravanireddy1102 Issues is already assigned
