### ISSUE TITLE
Trie | Data Structures | C++

### ISSUE THREAD

**Issue by SoumyaMalgonde** [Py-Contributors/AlgorithmsAndDataStructure#781]
### **Trie**

**What will change -**
- Will add new code for trie in C++ language

**Type of Issue -**

- [x]  Adding New Code

**Programming Language**
- C++

**Self Check**

- [x] Ask for issue assignment before making Pull Request.

- [x] Add your file in the proper folder

- [x] Clean Code and Documentation for better readability

- [x] Add Title and Description of the program in the file

🌟 Star it 🍴Fork it 🤝 Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SoumyaMalgonde** [comment]
I would like to contribute! Can I work on this issue?

**Comment by sswong0223** [comment]
Can you assign this issue to me?
