### ISSUE TITLE
Implement Linear Search in Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#8]
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** - Implement Linear Search in Python

**what will change** - Create a New Folder `SeacrhingAlgorithms` In Python/Algorithms

**Assignees** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request
Happy Coding,

**Comment by Jaideep07** [comment]
I would be glad to do this also 😃 can you assign it to me

**Comment by codeperfectplus** [comment]
- [x] @Jaideep07  Assigned Issue 

Happy Coding,
