### ISSUE TITLE
Tarjan's Algorithm | Graph | C++

### ISSUE THREAD

**Issue by Aditi-1400** [Py-Contributors/AlgorithmsAndDataStructure#80]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
### Programming Language

- [x] C++

### Self Check 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Aditi-1400** [comment]
Hey, Can I work on this as a part of Hacktoberfest?

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @Aditi-1400 

Make sure to raise the Pull request on 1st October or after it for valid Hacktober PR. 

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding,

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.
