### ISSUE TITLE
Klee's Algorithm | Geometry | Python

### ISSUE THREAD

**Issue by dhruval-tech** [Py-Contributors/AlgorithmsAndDataStructure#806]
## **`Klee's Algorithm`** - Length Of Union Of Segments of a line

**Description** -

Given starting and ending positions of segments on a line, the task is to take the union of all given segments and find length covered by these segments

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by dhruval-tech** [comment]
Please, assign this issue to me .

**Comment by absognety** [comment]
I have solved this, can give a PR on acknowledgment as it was issued to you.

**Comment by absognety** [comment]
I am very much interested in contributing to this repository, Please find my PR for this if it was un-assigned.
https://github.com/Py-Contributors/AlgorithmsAndDataStructure/pull/807
