### ISSUE TITLE
Data Structures | LinkedList | C++

### ISSUE THREAD

**Issue by Jashandeep2020** [Py-Contributors/AlgorithmsAndDataStructure#81]
## **`Title`** -

**Want to add new code in data structures folder under C++. (Linked List, Stack and Heap)** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Jashandeep2020** [comment]
**Want to make the contribution under Hacktoberfest.**

**Comment by codeperfectplus** [comment]
Valid PR for Hacktober will count from 1st October so make your PR on 1st October

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!
Happy Coding

**Comment by Jashandeep2020** [comment]
Thank you.

**Comment by kshitij9896** [comment]
Want to make the contribution under Hacktoberfest.

**Comment by SSKale1** [comment]
Please make a single issue for each contribution.

**Comment by SSKale1** [comment]
PR Merged, closing issue.
