### ISSUE TITLE
Patience Sort | Sorting Algorithm| Python

### ISSUE THREAD

**Issue by ghost** [Py-Contributors/AlgorithmsAndDataStructure#815]
## **`Title`** - Patience Sort

**what will change** - Adding Algorithm

### Type of Issue - Algorithm not present

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by patrick-bedkowski** [comment]
Hey! I would like to contribute some data structures and path finding algorithms.

**Comment by ghost** [comment]
can i work on this issue
