### ISSUE TITLE
Kadane's Algorithm | Dynamic Programming | C++

### ISSUE THREAD

**Issue by leonardoAnjos16** [Py-Contributors/AlgorithmsAndDataStructure#82]
## **`Title`** - Kadane's Algorithm

**what will change** - Will add Kadane's Algorithm for finding the maximum subarray sum in C++!

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by leonardoAnjos16** [comment]
I would like to work on this for Hacktoberfest, please!

**Comment by rafu01** [comment]
I would like to work on this

**Comment by shubham5351** [comment]
@leonardoAnjos16 you can work on this issue.

**Comment by D34DStone** [comment]
I want to work on this because of Hacktoberfest! @leonardoAnjos16

**Comment by SahilKumar47** [comment]
I would be happy to resolve this issue.  :)

**Comment by b4d-53ct0r** [comment]
I would love to work on this for Hacktoberfest !

**Comment by hacky1997** [comment]
@shubham5351 I would like to work it with python. Can you please assign me also?

**Comment by RajawatBanna** [comment]
i would like to solve this issue

**Comment by anushkrishnav** [comment]
I will work on python

**Comment by SSKale1** [comment]
PR Merged closing issue.
