### ISSUE TITLE
Kruskal Algorithm | Graph | C++

### ISSUE THREAD

**Issue by TiagoHRPG** [Py-Contributors/AlgorithmsAndDataStructure#827]
## **`Kruskal`** -

**what will change** - Used to search MST

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by gustavoaca1997** [comment]
Hi. I'd like to take this issue :)

**Comment by SubhayanDas08** [comment]
Please assign me this issue
