### ISSUE TITLE
Merge Sort | Sorting | C++

### ISSUE THREAD

**Issue by rafu01** [Py-Contributors/AlgorithmsAndDataStructure#83]
## **`Title`** - Merge sort in C++

**what will change** - I will add merge sort in c++ under sorting algorithms

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rafu01** [comment]
I would like to work on it

**Comment by shubham5351** [comment]
@rafu01 As this issue is already present please work on another issue.
