### ISSUE TITLE
Data Structures| Doubly Linked List | C++

### ISSUE THREAD

**Issue by AlKun25** [Py-Contributors/AlgorithmsAndDataStructure#84]
## **`Title`** - Doubly Linked List

**Want to add new code in data structures folder under C++. (Linked List) ** 

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AlKun25** [comment]
I would like this issue to be assigned to me. Would work on it for Hacktoberfest

**Comment by shubham5351** [comment]
@AlKun25 you can work on this issue.

**Comment by akshatgarg12** [comment]
Can i work on this issue?

**Comment by AlKun25** [comment]
Hi @akshatgarg12 ,
I am already working on this issue. Could you please work on some other issue or create a new one?
