### ISSUE TITLE
Fibonacci Numbers | Recursion | C++

### ISSUE THREAD

**Issue by rajdeep-ray** [Py-Contributors/AlgorithmsAndDataStructure#85]
## **`Title`** - Fibonacci Numbers | Recursion

I would like to add new code in the Algorithms folder for Recursion under C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by codeperfectplus** [comment]
@Rajdeep-Ray please be specific what code you want to add under recursion.

Algorithm_name | Category | Language
example:
Fibonacci series | Recursion | C++

**Comment by rajdeep-ray** [comment]
I would like to work on this issue under Hacktoberfest 2020.

**Comment by codeperfectplus** [comment]
- [x] issue assigned to @Rajdeep-Ray 

Happy Coding

**Comment by sourabmaity** [comment]
I would like to work

**Comment by SSKale1** [comment]
Similar PR already merged.
