### ISSUE TITLE
Level order traversal | Trees | C++

### ISSUE THREAD

**Issue by MaddieBrewer1** [Py-Contributors/AlgorithmsAndDataStructure#858]
## **`Level order traversal of binary tree`** -

**what will change** - I would like to add code for level order traversal of a binary tree

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by MaddieBrewer1** [comment]
hello, Im an undergrad student hoping to contribute to an open source project for a class assignment, could I please be assigned to add this? I looked through the files to see if it was already implemented and from what I saw it wasn't.

**Comment by codeperfectplus** [comment]
@MaddieBrewer1 - [ ] Issue Assigned. 
Happy Coding,
