### ISSUE TITLE
Kruskal & Prims | MST | C++

### ISSUE THREAD

**Issue by rafu01** [Py-Contributors/AlgorithmsAndDataStructure#86]
## **`Title`** - Kruskal, Prims algorithm for minimum spanning tree

**what will change** - I will add the code for Kruskal and Prims algorithm

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rafu01** [comment]
I want to work on it please

**Comment by niki-beep** [comment]
I want to work on it.
