### ISSUE TITLE
Fibonacci List | Recursion | C++

### ISSUE THREAD

**Issue by rajdeep-ray** [Py-Contributors/AlgorithmsAndDataStructure#87]
## **`Title`** - Fibonacci List | Recursion

I would like to add new code in the Algorithms folder for Recursion under C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rajdeep-ray** [comment]
I would like to work on this issue

**Comment by niki-beep** [comment]
I would like to work on this issue

**Comment by sourabmaity** [comment]
i would like to work on this issue

**Comment by codeperfectplus** [comment]
@niki-beep , @SOURAB-BAPPA 
The issue already assigned. new issues coming soon

**Comment by SSKale1** [comment]
Closing Issue PR Merged.
