### ISSUE TITLE
Slow Sort Algorithm | Sorting | Python

### ISSUE THREAD

**Issue by ajjayymahato** [Py-Contributors/AlgorithmsAndDataStructure#878]
## **`Slow Sort Algorithm`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [  ] Improving Code
- [  ] Improving Documentation
- [  ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [  ] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ajjayymahato** [comment]
Please assign this issue to me.

**Comment by Anuj-Kumar-AJ** [comment]
Hi @DrakeEntity , It seems it issue is open to work. So i am self-assigning this issue.

**Comment by Anuj-Kumar-AJ** [comment]
[``](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/pull/916/commits/51e68327aa89443d07b9607df921b60798c08211
)
