### ISSUE TITLE
Generate Spiral Matrix | Data Structure | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#88]
## **`Title`** - Generate the spiral matrix for the given number n

Input : Take the input n from the user and fill the matrix from 1 to n^2 in spiral form.

3

[ [1, 2, 3],
  [8, 9, 4],
  [7, 6, 5] ]

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
i want to solve this issue

**Comment by shubham5351** [comment]
@SOURAB-BAPPA I have assigned you this issue you can work on this.

**Comment by sourabmaity** [comment]
yup

**Comment by pradumio** [comment]
I want to solve this issue
