### ISSUE TITLE
README - proofreading 

### ISSUE THREAD

**Issue by jesslyw** [Py-Contributors/AlgorithmsAndDataStructure#880]
## **`Title`** - README - proofreading and improvement 

**what will change** - Correcting grammar and readability issues for better project documentation :) 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Documentation

### Programming Language

-

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by danschenker** [comment]
This is absolutely my bread and butter. I'd be happy to take on a proofreading task if you'll have me @jeslyw !

**Comment by jesslyw** [comment]
Sorry, I forgot to mention I wanted to be assigned the issue but we can work on it together

**Comment by danschenker** [comment]
> Sorry, I forgot to mention I wanted to be assigned the issue but we can work on it together

It's fine by me! I'm still sort of getting my feet wet with open source, but proofreading is something I'm pretty comfortable with. Just let me know where you need me!

**Comment by anirudh0806** [comment]
I am interested in this work. I would love to contribute. Could you please assign the issue?

**Comment by danschenker** [comment]
> jeslyw

I made a round of edits this morning, but I already see something I missed on Line 43. Do you want to take another pass through it?

**Comment by jesslyw** [comment]
Yes. Will fork the edited version once @codePerfectPlus merges your PR

**Comment by codeperfectplus** [comment]
PR #884 is merged. Thanks for your amazing contribution.
