### ISSUE TITLE
Trie Data Structure | Data Structure | C++

### ISSUE THREAD

**Issue by adityaajay29** [Py-Contributors/AlgorithmsAndDataStructure#883]
## **`Title`** -
Add Trie Data Structure in C++
**what will change** -
Trie Data Structure will be added to the c++ DS folder, currently missing
### Type of Issue -
Addition of new Data Structure
Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by ZahraShahid** [comment]
Can I work on this issue? @adityaajay29

**Comment by abhinavjoshicse** [comment]
Hey! I'm interested in this and would like to contribute , Please assign this to me.

**Comment by adityaajay29** [comment]
@ZahraShahid I can't assign, I am also looking to contribute

**Comment by adityaajay29** [comment]
> Can I work on this issue? @adityaajay29
I can't assign, I am also looking to contribute

**Comment by codeperfectplus** [comment]
@ZahraShahid, @Abhinav-J05 

You guys can create a new issue for adding a new algorithm or fix the previous one.

Happy Hacktoberfest.

**Comment by Ishika610** [comment]
hey @adityaajay29 i would like to work on this issue. could you please assign this to me?
