### ISSUE TITLE
Interpolation Search | Algorithms | C++

### ISSUE THREAD

**Issue by Pranshu321** [Py-Contributors/AlgorithmsAndDataStructure#885]
## **`Interpolation Search`** -

**what will change** -
In, this I will explain how **interpolation search** works, its clean code with useful comments, and its beginner-friendly code style.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by deepesh85b** [comment]
@Pranshu321 
Please assign this to me
