### ISSUE TITLE
Hamiltonian Cycle | Backtracking | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#89]
## **`Title`** - Hamiltonian Cycle | Backtracking | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by meghanacosmos** [comment]
I would like to work on this, could you assign this issue to me?

**Comment by jayitsaha** [comment]
Can I be assigned this Issue, I am done with the solution and can send a PR .

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @Meghana-12
