### ISSUE TITLE
WildcardPattern.cpp | DSA/cpp |C++

### ISSUE THREAD

**Issue by engineervt** [Py-Contributors/AlgorithmsAndDataStructure#891]
## **`WildcardPattern.cpp`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

-
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Sakshi2002-Sinha** [comment]
Can you assign me this issue?

**Comment by codeperfectplus** [comment]
@Sakshi2002-Sinha This issue is already completed. This repo is excluded from Hacktoberfest. please check other repo for contributions.
