### ISSUE TITLE
Insertion sort | DSA | JavaScript

### ISSUE THREAD

**Issue by tinniaru3005** [Py-Contributors/AlgorithmsAndDataStructure#896]
## **`Title`** -
Add insertion sort algorithm in JavaScript
**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] JavaScript

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by tinniaru3005** [comment]
Can you please assign it to me?

**Comment by Ishikasaraf20** [comment]
hey @py-contributors-official can you assign this issue to me i can work on it

**Comment by codeperfectplus** [comment]
@Ishikasaraf20 issue is assigned to the author. You can create a new issue. There is a lot of algorithms and  Data structure that still needs to update.
