### ISSUE TITLE
print all permutations of a given string | Backtracking | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#90]
## **`Title`** - print all permutations of a given string

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rafu01** [comment]
I would like to work on this

**Comment by codeperfectplus** [comment]
- [x] assigning task to @rafu01

**Comment by SSKale1** [comment]
Merged PR. Closing Issue.
