### ISSUE TITLE
Counting sort | DSA | JavaScript

### ISSUE THREAD

**Issue by tinniaru3005** [Py-Contributors/AlgorithmsAndDataStructure#900]
## **`Title`** -
Add counting sort algorithm in JavaScript
**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] JavaScript

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Ishikasaraf20** [comment]
hey @tinniaru3005 can you assign this issue to me i can work on it

**Comment by Ashpreetwadhwa** [comment]
I am interested in this task

**Comment by codeperfectplus** [comment]
Generally, the issue is assigned to the author. Please confirm @tinniaru3005 if you are working on this issue.

**Comment by tinniaru3005** [comment]
> Generally, the issue is assigned to the author. Please confirm @tinniaru3005 if you are working on this issue.

Hey @codePerfectPlus I would like to work on the issue. But there are a lot of other algorithms such as search algorithms, hashing algorithms, and other algo based on tree, linkedlist, array, heap, etc. that can be added in JavaScript. so, @Ashpreetwadhwa and @Ishikasaraf20 may be you can raise an issue for them and add it. :)
