### ISSUE TITLE
print all permutations of a given string | Backtracking | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#91]
## **`Title`** - print all permutations of a given string | Backtracking | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sourabmaity** [comment]
I want to code for this

**Comment by codeperfectplus** [comment]
- [x] Issue assigning to  @SOURAB-BAPPA

**Comment by rafa-ribeiro** [comment]
Hello guys! 

I would like to contribute to this issue if it's possible. Thank you very much.
