### ISSUE TITLE
Find the eulerian path | Algorithms | Python

### ISSUE THREAD

**Issue by shubham5351** [Py-Contributors/AlgorithmsAndDataStructure#93]
## **`Title`** - Find the Eulerian path in the given graph.

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [✓] Adding New Code
- [✓] Improving Code
- [✓] Improving Documentation
- [✓] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by meghanacosmos** [comment]
I would like to work on this @codePerfectPlus

**Comment by shubham5351** [comment]
@Meghana-12 you can work on this issue.
