### ISSUE TITLE
Shortest Job First Algorithm | Scheduling Algorithm | Python

### ISSUE THREAD

**Issue by johannesteshome** [Py-Contributors/AlgorithmsAndDataStructure#930]
## **`Add Shortest Job First Algorithm in the Scheduling Algorithm Section`** -

**what will change** - Add new code in the scheduling algorithm category

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by Itachi0906** [comment]
hey @John-droid-dotcom , Can I be assigned this issue

**Comment by johannesteshome** [comment]
I was asking to be assigned to this issue.

**Comment by Itachi0906** [comment]
okk , my bad
