### ISSUE TITLE
Counting Sort | Sorting Algorithm | Python

### ISSUE THREAD

**Issue by yohannesME** [Py-Contributors/AlgorithmsAndDataStructure#932]
## **`Title`** - Add Counting Sort Algorithm to Sorting Algorithms

**what will change**
- The addition of the Counting Sort algorithm to the list of sorting algorithms in the repository.
- A new implementation file will be added for Counting Sort, along with the necessary unit tests.
- The existing sorting algorithm implementations and tests will not be affected by this change.
- Users of the repository will have access to a simple and efficient sorting algorithm that can handle large ranges of input values.

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] Python
- [x] C++
- [x] Java
- [x] JavaScript

**Comment by yohannesME** [comment]
I was also wondering to be assigned to this issue, i can implement and add the algorithm in all of the languages.

**Comment by AfaqShuaib09** [comment]
Hey, Could you this issue to me?. I would love to make a PR on this issue
Thanks

**Comment by yohannesME** [comment]
I was hoping to do it myself, as I am very familiar with the algorithm.

**Comment by AfaqShuaib09** [comment]
oh.. okay, no worries. Is there any other issue that I can pick up

**Comment by yohannesME** [comment]
most of the algorithms that are implemented are mostly in python, if you are interested you can add then in other languages as well.

**Comment by shreya020703** [comment]
I'll take this up, to solve this issue in python

**Comment by Kritika30032002** [comment]
Are you solving this? @shreya020703
