### ISSUE TITLE
Slow Sort | Sorting Algorithm | Javascript

### ISSUE THREAD

**Issue by AfaqShuaib09** [Py-Contributors/AlgorithmsAndDataStructure#933]
## **`Title`** - Add Slow Sort to the sorting Algo

**what will change** -
- The addition of the Slow Sort algorithm to the list of sorting algorithms in the repository.
- A new implementation file will be added for Slow Sort, along with the necessary unit tests.
- The existing sorting algorithm implementations and tests will not be affected by this change.
- Users of the repository will have access to a simple and efficient sorting algorithm that can handle large ranges of input values.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
- [x] JavaScript (JS)

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by AfaqShuaib09** [comment]
Hey @codeperfectplus, Could you assign me this issue?
Thank you!

**Comment by Kritika30032002** [comment]
@AfaqShuaib09  You can Now work on it.
