### ISSUE TITLE
Prim’s Minimum Spanning Tree | GreedyAlgorithm | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#94]
## **`Title`** - Prim’s Minimum Spanning Tree | GreedyAlgorithm | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by utkarshbajaj** [comment]
Hey! I'd like to take this up

**Comment by codeperfectplus** [comment]
you have already assigned to some task already. give a chance to contribute to others too @utkarshbajaj

**Comment by rafu01** [comment]
A similar issue has been created already #86

**Comment by codeperfectplus** [comment]
@rafu01 Thanks for pointing out the issue

**Comment by utkarshbajaj** [comment]
> you have already assigned to some task already. give a chance to contribute to others too @utkarshbajaj

Sure
