### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by sreyaarc** [Py-Contributors/AlgorithmsAndDataStructure#940]
## **`Typo in readme.md file`** -

**what will change** -
The readme.md says A Collection of Algorithm And Data Structures in C++ and Python

Changing it to:  A Collection of Algorithms And Data Structures in C++ and Python

### Type of Issue - typo

Please add/delete options that are not relevant.

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by sreyaarc** [comment]
Please assign this issue to me.

**Comment by Abhishekm0410** [comment]
Please assign this issue to me
