### ISSUE TITLE
Prim’s Minimum Spanning Tree | GreedyAlgorithm | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#95]
## **`Title`** - Prim’s Minimum Spanning Tree | GreedyAlgorithm | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by rafu01** [comment]
I'm working on a similar issue #86 
Can I do this too?

**Comment by ghost** [comment]
Can I get this issue Assigned? :D

**Comment by codePerfectPlus** [comment]
- [x]  Issue assigned @p014ri5
