### ISSUE TITLE
Sieve of Sundaram to print all primes smaller than n | Sieve Algorithm | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#96]
## **`Title`** - Sieve of Sundaram to print all primes smaller than n | Sieve Algorithm | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by nishant-mor** [comment]
I would like to work on this

**Comment by shubham5351** [comment]
@nishant-mor you can work on this.
