### ISSUE TITLE
Sieve of Sundaram to print all primes smaller than n | Sieve Algorithm | Python

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#97]
## **`Title`** - Sieve of Sundaram to print all primes smaller than n | Sieve Algorithm | Python

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by utkarshbajaj** [comment]
Hey! I'd like to take this up

**Comment by codePerfectPlus** [comment]
you have already assigned to some task already. give a chance to contribute to others too @utkarshbajaj

**Comment by Aveek-Saha** [comment]
Can I start working on this issue?

**Comment by codeperfectplus** [comment]
- [x] Assigning issue to @Aveek-Saha
