### ISSUE TITLE
Exponential Search | Searching Algorithm | C++

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/AlgorithmsAndDataStructure#99]
## **`Title`** - Exponential Search | Searching Algorithm | C++

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

**Comment by SuvamPrasd** [comment]
The repo is well structured and great for the developers. I find this repo helpful so I want to contribute to this repo and help the community. I want to work on this **issue#99**. @codePerfectPlus

**Comment by codeperfectplus** [comment]
Implementing Data Structures and Algorithms for learning purpose. it will be helpful to a lot of students.

[x] assigning the issue to @SuvamPrasd 

Check other repo for contributions - https://github.com/py-contributors/awesomescripts

**Comment by SuvamPrasd** [comment]
Thanks for assigning me this issue.

**Comment by SSKale1** [comment]
PR Merged. Closing Issue.
